/*

 Thanks to http://davidwalsh.name/crud-javascript-class
 Vanilla JS equivalent to $.extend
*/
window.extend=function(f,m){f=f||{};if(2<arguments.length)for(var b=1;b<arguments.length;b++)window.extend(f,arguments[b]);else for(b in m)f[b]=m[b];return f};
"function"==typeof JSON.parse&&window.localStorage&&window.sessionStorage&&function(f,m){var b=function(a){this.conf=extend({name:"database",indexedKeys:[],uniqueKey:"id",driver:new b.drivers.StorageDriver({name:a.name,storage:f.localStorage})},a||{});this.initialize()};b.prototype.initialize=function(){this.data=this.load()||[];this.id=0;0<this.data.length&&(this.data=this.data.map(function(a){return parseInt(a,10)}),this.id=Math.max.apply(Math,this.data))};b.prototype.find=function(a){if("undefined"===
typeof a)return this.findAll();a=this.getKeys(a);var c=[],d;for(d in a[0])c.push(this.conf.driver.getItem(d+":"+a[0][d])||!1);d=0===c.length?this.data:1===c.length?c[0]:n.apply(this,c);return this.filter(this.select(d),a[1])};b.prototype.findAll=function(){return this.select(this.data)};b.prototype.getKeys=function(a){var c,d=[{},{}],e;for(e in a)c=-1!==this.conf.indexedKeys.indexOf(e)?0:1,d[c][e]=a[e];return d};b.prototype.select=function(a){var c=[];a=1===a.length?[a]:a;for(var d=0,e=a.length;d<
e;d++)c.push(this.conf.driver.getItem(a[d]));return c};b.prototype.filter=function(a,c){for(var d,e,b=[],f=0,h=a.length;f<h;f++){e=a[f];d=!0;for(var k in c)if(e[k]!==c[k]){d=!1;break}d&&b.push(e)}return b};b.prototype.insert=function(a){if("[object Object]"!==Object.prototype.toString.call(a))throw"Can't insert "+a+". Please insert object.";this.id++;if(-1===this.data.indexOf(this.id))return a[this.conf.uniqueKey]=this.id,this.data.push(this.id),this.conf.driver.setItem(this.id,a),this.conf.driver.setItem("__data",
this.data.join(",")),this.buildIndex(a),this.id};b.prototype.update=function(a,c){if(-1!==this.data.indexOf(a))return this.destroyIndex(a),c[this.conf.uniqueKey]=a,this.conf.driver.setItem(a,c),this.buildIndex(c),c};b.prototype["delete"]=function(a){if("[object Object]"===Object.prototype.toString.call(a))this.findAndDelete(a);else if(-1!==this.data.indexOf(a))return this.data.splice(this.data.indexOf(a),1),this.destroyIndex(a),this.conf.driver.removeItem(a),this.conf.driver.setItem("__data",this.data.join(",")),
-1===this.data.indexOf(a)};b.prototype.findAndDelete=function(a){for(var c=this.find(a),d=this.data.length,e=0;e<c.length;e++)a=c[e][this.conf.uniqueKey],-1!==this.data.indexOf(a)&&(this.data.splice(this.data.indexOf(a),1),this.destroyIndex(a),this.conf.driver.removeItem(a),this.conf.driver.setItem("__data",this.data.join(",")));return this.data.length<d};b.prototype.count=function(){return this.data.length};b.prototype.drop=function(){for(var a=0,c=this.data.length;a<c;a++)this["delete"](this.data[a]);
this.conf.driver.removeItem("__data");this.data.length=0;return 0===this.data.length};b.prototype.load=function(){return this.conf.driver.getItem("__data")?this.conf.driver.getItem("__data").split(","):null};b.prototype.buildIndex=function(a){var c,d,e,b;for(b in a)-1!==this.conf.indexedKeys.indexOf(b)&&(e=[a[this.conf.uniqueKey]],c=b+":"+a[b],d=this.conf.driver.getItem(c),null!==d&&(d.push(a[this.conf.uniqueKey]),e=d),this.conf.driver.setItem(c,e))};b.prototype.destroyIndex=function(a){var c,d,b=
this.conf.driver.getItem(a);if(null!==b)for(var f in b)-1!==this.conf.indexedKeys.indexOf(f)&&(c=f+":"+b[f],d=this.conf.driver.getItem(c),null!==d&&(d.splice(d.indexOf(a),1),0===d.length?this.conf.driver.removeItem(c):this.conf.driver.setItem(c,d)))};var n=function(){var a,c,b,e,f=[],g={},h;h=arguments.length-1;b=arguments[0].length;for(a=c=0;a<=h;a++)e=arguments[a].length,e<b&&(c=a,b=e);for(a=0;a<=h;a++){e=a===c?0:a||c;b=arguments[e].length;for(var k=0;k<b;k++){var l=arguments[e][k];g[l]===a-1?a===
h?(f.push(l),g[l]=0):g[l]=a:0===a&&(g[l]=0)}}return f};f.Database=b;f.Database.drivers={};var g=function(a){this.conf=f.extend({name:"",storage:f.localStorage},a||{});if("function"!==typeof a.storage.getItem||"function"!==typeof a.storage.removeItem||"function"!==typeof a.storage.setItem)throw"Given Storage doesn't have methods `getItem`, `setItem` and `removeItem`.";};g.prototype.setItem=function(a,b){return this.conf.storage.setItem(this.conf.name+":"+a,JSON.stringify(b))};g.prototype.getItem=function(a){return JSON.parse(this.conf.storage.getItem(this.conf.name+
":"+a))};g.prototype.removeItem=function(a){return this.conf.storage.removeItem(this.conf.name+":"+a)};f.Database&&(f.Database.drivers.StorageDriver=g)}(window);
