/*

 Modernizr 2.8.2 (Custom Build) | MIT & BSD

 Build:http://modernizr.com/download/#-fontface-backgroundsize-borderimage-borderradius-boxshadow-flexbox-flexboxlegacy-hsla-multiplebgs-opacity-rgba-textshadow-cssanimations-csscolumns-generatedcontent-cssgradients-cssreflections-csstransforms-csstransforms3d-csstransitions-applicationcache-canvas-canvastext-draganddrop-hashchange-history-audio-video-indexeddb-input-inputtypes-localstorage-postmessage-sessionstorage-websockets-websqldatabase-webworkers-geolocation-inlinesvg-svg-svgclippaths-touch-shiv-cssclasses-teststyles-testprop-testallprops-hasevent-prefixes-domprefixes-load

*/
window.Modernizr=function(k,e,y){function v(a,b){return typeof a===b}function C(a,b){for(var d in a){var r=a[d];if(!~(""+r).indexOf("-")&&m[r]!==y)return"pfx"==b?r:!0}return!1}function p(a,b,d){var r=a.charAt(0).toUpperCase()+a.slice(1),c=(a+" "+D.join(r+" ")+r).split(" ");if(v(b,"string")||v(b,"undefined"))b=C(c,b);else a:{c=(a+" "+E.join(r+" ")+r).split(" "),a=c;for(var e in a)if(r=b[a[e]],r!==y){b=!1===d?a[e]:v(r,"function")?r.bind(d||b):r;break a}b=!1}return b}function P(){f.input=function(a){for(var b=
0,d=a.length;b<d;b++)F[a[b]]=a[b]in h;return F.list&&(F.list=!!e.createElement("datalist")&&!!k.HTMLDataListElement),F}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));f.inputtypes=function(a){for(var b=0,d,r,c,f=a.length;b<f;b++)h.setAttribute("type",r=a[b]),(d="text"!==h.type)&&(h.value=x,h.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(r)&&h.style.WebkitAppearance!==y?(w.appendChild(h),c=e.defaultView,d=c.getComputedStyle&&"textfield"!==
c.getComputedStyle(h,null).WebkitAppearance&&0!==h.offsetHeight,w.removeChild(h)):/^(search|tel)$/.test(r)||(/^(url|email)$/.test(r)?d=h.checkValidity&&!1===h.checkValidity():d=h.value!=x)),O[a[b]]=!!d;return O}("search tel url email datetime date month week time datetime-local number range color".split(" "))}var f={},w=e.documentElement,c=e.createElement("modernizr"),m=c.style,h=e.createElement("input"),x=":)",z={}.toString,A=" -webkit- -moz- -o- -ms- ".split(" "),D=["Webkit","Moz","O","ms"],E=["webkit",
"moz","o","ms"],c={},O={},F={},H=[],I=H.slice,J,B=function(a,b,d,r){var c,f,h,l,t=e.createElement("div"),n=e.body,u=n||e.createElement("body");if(parseInt(d,10))for(;d--;)h=e.createElement("div"),h.id=r?r[d]:"modernizr"+(d+1),t.appendChild(h);return c=['&#173;<style id="smodernizr">',a,"</style>"].join(""),t.id="modernizr",(n?t:u).innerHTML+=c,u.appendChild(t),n||(u.style.background="",u.style.overflow="hidden",l=w.style.overflow,w.style.overflow="hidden",w.appendChild(u)),f=b(t,a),n?t.parentNode.removeChild(t):
(u.parentNode.removeChild(u),w.style.overflow=l),!!f},K=function(){var a={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(b,d){d=d||e.createElement(a[b]||"div");b="on"+b;var c=b in d;return c||(d.setAttribute||(d=e.createElement("div")),d.setAttribute&&d.removeAttribute&&(d.setAttribute(b,""),c=v(d[b],"function"),v(d[b],"undefined")||(d[b]=y),d.removeAttribute(b))),c}}(),q={}.hasOwnProperty,G;v(q,"undefined")||v(q.call,"undefined")?G=function(a,
b){return b in a&&v(a.constructor.prototype[b],"undefined")}:G=function(a,b){return q.call(a,b)};Function.prototype.bind||(Function.prototype.bind=function(a){var b=this;if("function"!=typeof b)throw new TypeError;var d=I.call(arguments,1),c=function(){if(this instanceof c){var e=function(){};e.prototype=b.prototype;var e=new e,f=b.apply(e,d.concat(I.call(arguments)));return Object(f)===f?f:e}return b.apply(a,d.concat(I.call(arguments)))};return c});c.flexbox=function(){return p("flexWrap")};c.flexboxlegacy=
function(){return p("boxDirection")};c.canvas=function(){var a=e.createElement("canvas");return!!a.getContext&&!!a.getContext("2d")};c.canvastext=function(){return!!f.canvas&&!!v(e.createElement("canvas").getContext("2d").fillText,"function")};c.touch=function(){var a;return"ontouchstart"in k||k.DocumentTouch&&e instanceof DocumentTouch?a=!0:B(["@media (",A.join("touch-enabled),("),"modernizr){#modernizr{top:9px;position:absolute}}"].join(""),function(b){a=9===b.offsetTop}),a};c.geolocation=function(){return"geolocation"in
navigator};c.postmessage=function(){return!!k.postMessage};c.websqldatabase=function(){return!!k.openDatabase};c.indexedDB=function(){return!!p("indexedDB",k)};c.hashchange=function(){return K("hashchange",k)&&(e.documentMode===y||7<e.documentMode)};c.history=function(){return!!k.history&&!!history.pushState};c.draganddrop=function(){var a=e.createElement("div");return"draggable"in a||"ondragstart"in a&&"ondrop"in a};c.websockets=function(){return"WebSocket"in k||"MozWebSocket"in k};c.rgba=function(){m.cssText=
"background-color:rgba(150,255,150,.5)";return!!~(""+m.backgroundColor).indexOf("rgba")};c.hsla=function(){m.cssText="background-color:hsla(120,40%,100%,.5)";return!!~(""+m.backgroundColor).indexOf("rgba")||!!~(""+m.backgroundColor).indexOf("hsla")};c.multiplebgs=function(){m.cssText="background:url(https://),url(https://),red url(https://)";return/(url\s*\(.*?){3}/.test(m.background)};c.backgroundsize=function(){return p("backgroundSize")};c.borderimage=function(){return p("borderImage")};c.borderradius=
function(){return p("borderRadius")};c.boxshadow=function(){return p("boxShadow")};c.textshadow=function(){return""===e.createElement("div").style.textShadow};c.opacity=function(){var a=A.join("opacity:.55;")+"";m.cssText=a;return/^0.55$/.test(m.opacity)};c.cssanimations=function(){return p("animationName")};c.csscolumns=function(){return p("columnCount")};c.cssgradients=function(){var a=("background-image:-webkit-gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:"+A.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,
-17);m.cssText=a;return!!~(""+m.backgroundImage).indexOf("gradient")};c.cssreflections=function(){return p("boxReflect")};c.csstransforms=function(){return!!p("transform")};c.csstransforms3d=function(){var a=!!p("perspective");return a&&"webkitPerspective"in w.style&&B("@media (transform-3d),(-webkit-transform-3d){#modernizr{left:9px;position:absolute;height:3px;}}",function(b,d){a=9===b.offsetLeft&&3===b.offsetHeight}),a};c.csstransitions=function(){return p("transition")};c.fontface=function(){var a;
return B('@font-face {font-family:"font";src:url("https://")}',function(b,d){var c=e.getElementById("smodernizr"),c=(c=c.sheet||c.styleSheet)?c.cssRules&&c.cssRules[0]?c.cssRules[0].cssText:c.cssText||"":"";a=/src/i.test(c)&&0===c.indexOf(d.split(" ")[0])}),a};c.generatedcontent=function(){var a;return B(['#modernizr{font:0/0 a}#modernizr:after{content:"',x,'";visibility:hidden;font:3px/1 a}'].join(""),function(b){a=3<=b.offsetHeight}),a};c.video=function(){var a=e.createElement("video"),b=!1;try{if(b=
!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,""),b.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,""),b.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,"")}catch(c){}return b};c.audio=function(){var a=e.createElement("audio"),b=!1;try{if(b=!!a.canPlayType)b=new Boolean(b),b.ogg=a.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,""),b.mp3=a.canPlayType("audio/mpeg;").replace(/^no$/,""),b.wav=a.canPlayType('audio/wav; codecs="1"').replace(/^no$/,
""),b.m4a=(a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;")).replace(/^no$/,"")}catch(c){}return b};c.localstorage=function(){try{return localStorage.setItem("modernizr","modernizr"),localStorage.removeItem("modernizr"),!0}catch(a){return!1}};c.sessionstorage=function(){try{return sessionStorage.setItem("modernizr","modernizr"),sessionStorage.removeItem("modernizr"),!0}catch(a){return!1}};c.webworkers=function(){return!!k.Worker};c.applicationcache=function(){return!!k.applicationCache};
c.svg=function(){return!!e.createElementNS&&!!e.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect};c.inlinesvg=function(){var a=e.createElement("div");return a.innerHTML="<svg/>","http://www.w3.org/2000/svg"==(a.firstChild&&a.firstChild.namespaceURI)};c.svgclippaths=function(){return!!e.createElementNS&&/SVGClipPath/.test(z.call(e.createElementNS("http://www.w3.org/2000/svg","clipPath")))};for(var L in c)G(c,L)&&(J=L.toLowerCase(),f[J]=c[L](),H.push((f[J]?"":"no-")+J));f.input||P();
f.addTest=function(a,b){if("object"==typeof a)for(var c in a)G(a,c)&&f.addTest(c,a[c]);else{a=a.toLowerCase();if(f[a]!==y)return f;b="function"==typeof b?b():b;w.className+=" "+(b?"":"no-")+a;f[a]=b}return f};m.cssText="";return c=h=null,function(a,b){function c(){var b=m.elements;return"string"==typeof b?b.split(" "):b}function e(b){var a=g[b[p]];return a||(a={},M++,b[p]=M,g[M]=a),a}function f(a,c,d){c||(c=b);if(N)return c.createElement(a);d||(d=e(c));var g;return d.cache[a]?g=d.cache[a].cloneNode():
n.test(a)?g=(d.cache[a]=d.createElem(a)).cloneNode():g=d.createElem(a),!g.canHaveChildren||t.test(a)||g.tagUrn?g:d.frag.appendChild(g)}function h(b,a){a.cache||(a.cache={},a.createElem=b.createElement,a.createFrag=b.createDocumentFragment,a.frag=a.createFrag());b.createElement=function(c){return m.shivMethods?f(c,b,a):a.createElem(c)};b.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+c().join().replace(/[\w\-]+/g,function(b){return a.createElem(b),
a.frag.createElement(b),'c("'+b+'")'})+");return n}")(m,a.frag)}function k(a){a||(a=b);var c=e(a);if(m.shivCSS&&!u&&!c.hasCSS){var d,g=a;d=g.createElement("p");g=g.getElementsByTagName("head")[0]||g.documentElement;d=(d.innerHTML="x<style>article,aside,dialog,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}mark{background:#FF0;color:#000}template{display:none}</style>",g.insertBefore(d.lastChild,g.firstChild));c.hasCSS=!!d}return N||h(a,c),a}var l=a.html5||{},t=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,
n=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,u,p="_html5shiv",M=0,g={},N;(function(){try{var a=b.createElement("a");a.innerHTML="<xyz></xyz>";u="hidden"in a;var c;if(!(c=1==a.childNodes.length)){b.createElement("a");var d=b.createDocumentFragment();c="undefined"==typeof d.cloneNode||"undefined"==typeof d.createDocumentFragment||"undefined"==typeof d.createElement}N=c}catch(g){N=u=!0}})();var m={elements:l.elements||"abbr article aside audio bdi canvas data datalist details dialog figcaption figure footer header hgroup main mark meter nav output progress section summary template time video",
version:"3.7.0",shivCSS:!1!==l.shivCSS,supportsUnknownElements:N,shivMethods:!1!==l.shivMethods,type:"default",shivDocument:k,createElement:f,createDocumentFragment:function(a,g){a||(a=b);if(N)return a.createDocumentFragment();g=g||e(a);for(var n=g.frag.cloneNode(),f=0,t=c(),u=t.length;f<u;f++)n.createElement(t[f]);return n}};a.html5=m;k(b)}(this,e),f._version="2.8.2",f._prefixes=A,f._domPrefixes=E,f._cssomPrefixes=D,f.hasEvent=K,f.testProp=function(a){return C([a])},f.testAllProps=p,f.testStyles=
B,w.className=w.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(" js "+H.join(" ")),f}(this,this.document);
(function(k,e,y){function v(b){return"[object Function]"==A.call(b)}function C(b){return"string"==typeof b}function p(){}function P(b){return!b||"loaded"==b||"complete"==b||"uninitialized"==b}function f(){var b=D.shift();E=1;b?b.t?x(function(){("c"==b.t?a.injectCss:a.injectJs)(b.s,0,b.a,b.x,b.e,1)},0):(b(),f()):E=0}function w(b,c,r,h,k,m,l){function t(a){if(!u&&P(n.readyState)&&(M.r=u=1,!E&&f(),n.onload=n.onreadystatechange=null,a)){"img"!=b&&x(function(){H.removeChild(n)},50);for(var e in q[c])q[c].hasOwnProperty(e)&&
q[c][e].onload()}}l=l||a.errorTimeout;var n=e.createElement(b),u=0,p=0,M={t:r,s:c,e:k,a:m,x:l};1===q[c]&&(p=1,q[c]=[]);"object"==b?n.data=c:(n.src=c,n.type=b);n.width=n.height="0";n.onerror=n.onload=n.onreadystatechange=function(){t.call(this,p)};D.splice(h,0,M);"img"!=b&&(p||2===q[c]?(H.insertBefore(n,F?null:z),x(t,l)):q[c].push(n))}function c(b,a,c,e,h){return E=0,a=a||"j",C(b)?w("c"==a?J:I,b,a,this.i++,c,e,h):(D.splice(this.i++,0,b),1==D.length&&f()),this}function m(){var b=a;return b.loader={load:c,
i:0},b}var h=e.documentElement,x=k.setTimeout,z=e.getElementsByTagName("script")[0],A={}.toString,D=[],E=0,O="MozAppearance"in h.style,F=O&&!!e.createRange().compareNode,H=F?h:z.parentNode,h=k.opera&&"[object Opera]"==A.call(k.opera),h=!!e.attachEvent&&!h,I=O?"object":h?"script":"img",J=h?"script":I,B=Array.isArray||function(b){return"[object Array]"==A.call(b)},K=[],q={},G={timeout:function(b,a){return a.length&&(b.timeout=a[0]),b}},L,a;a=function(b){function c(b){b=b.split("!");var a=K.length,d=
b.pop(),e=b.length,d={url:d,origUrl:d,prefixes:b},f,g,h;for(g=0;g<e;g++)h=b[g].split("="),(f=G[h.shift()])&&(d=f(d,h));for(g=0;g<a;g++)d=K[g](d);return d}function e(b,a,f,h,k){var g=c(b),l=g.autoCallback;g.url.split(".").pop().split("?").shift();g.bypass||(a&&(a=v(a)?a:a[b]||a[h]||a[b.split("/").pop().split("?")[0]]),g.instead?g.instead(b,a,f,h,k):(q[g.url]?g.noexec=!0:q[g.url]=1,f.load(g.url,g.forceCSS||!g.forceJS&&"css"==g.url.split(".").pop().split("?").shift()?"c":y,g.noexec,g.attrs,g.timeout),
(v(a)||v(l))&&f.load(function(){m();a&&a(g.origUrl,k,h);l&&l(g.origUrl,k,h);q[g.url]=2})))}function f(a,b){function c(a,f){if(a)if(C(a))f||(g=function(){var a=[].slice.call(arguments);k.apply(this,a);l()}),e(a,g,b,0,d);else{if(Object(a)===a)for(q in m=function(){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}(),a)a.hasOwnProperty(q)&&(!f&&!--m&&(v(g)?g=function(){var a=[].slice.call(arguments);k.apply(this,a);l()}:g[q]=function(a){return function(){var b=[].slice.call(arguments);a&&a.apply(this,
b);l()}}(k[q])),e(a[q],g,b,q,d))}else!f&&l()}var d=!!a.test,h=a.load||a.both,g=a.callback||p,k=g,l=a.complete||p,m,q;c(d?a.yep:a.nope,!!h);h&&c(h)}var h,k,l=this.yepnope.loader;if(C(b))e(b,0,l,0);else if(B(b))for(h=0;h<b.length;h++)k=b[h],C(k)?e(k,0,l,0):B(k)?a(k):Object(k)===k&&f(k,l);else Object(b)===b&&f(b,l)};a.addPrefix=function(a,c){G[a]=c};a.addFilter=function(a){K.push(a)};a.errorTimeout=1E4;null==e.readyState&&e.addEventListener&&(e.readyState="loading",e.addEventListener("DOMContentLoaded",
L=function(){e.removeEventListener("DOMContentLoaded",L,0);e.readyState="complete"},0));k.yepnope=m();k.yepnope.executeStack=f;k.yepnope.injectJs=function(b,c,h,k,m,q){var l=e.createElement("script"),t,n;k=k||a.errorTimeout;l.src=b;for(n in h)l.setAttribute(n,h[n]);c=q?f:c||p;l.onreadystatechange=l.onload=function(){!t&&P(l.readyState)&&(t=1,c(),l.onload=l.onreadystatechange=null)};x(function(){t||(t=1,c(1))},k);m?l.onload():z.parentNode.insertBefore(l,z)};k.yepnope.injectCss=function(a,c,h,k,m,q){k=
e.createElement("link");var l;c=q?f:c||p;k.href=a;k.rel="stylesheet";k.type="text/css";for(l in h)k.setAttribute(l,h[l]);m||(z.parentNode.insertBefore(k,z),x(c,0))}})(this,document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};
