language: php

php:
  #- 5.4 - commented because xsl doesn't load on travis server for unknown reason
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
    # php module
    #- echo "extension = xsl.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install: composer install
script: vendor/bin/phpunit
