/*

 jQuery JavaScript Library v1.10.2
 http://jquery.com/

 Includes Sizzle.js
 http://sizzlejs.com/

 Copyright 2005, 2013 jQuery Foundation, Inc. and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2013-07-03T13:48Z
*/
(function(t,n){function xa(a){var b=a.length,d=c.type(a);return c.isWindow(a)?!1:1===a.nodeType&&b?!0:"array"===d||"function"!==d&&(0===b||"number"===typeof b&&0<b&&b-1 in a)}function Ub(a){var b=Ta[a]={};c.each(a.match(F)||[],function(a,c){b[c]=!0});return b}function Ua(a,b,d,e){if(c.acceptData(a)){var f=c.expando,g=a.nodeType,h=g?c.cache:a,k=g?a[f]:a[f]&&f;if(k&&h[k]&&(e||h[k].data)||d!==n||"string"!==typeof b){k||(k=g?a[f]=ba.pop()||c.guid++:f);h[k]||(h[k]=g?{}:{toJSON:c.noop});if("object"===typeof b||
"function"===typeof b)e?h[k]=c.extend(h[k],b):h[k].data=c.extend(h[k].data,b);a=h[k];e||(a.data||(a.data={}),a=a.data);d!==n&&(a[c.camelCase(b)]=d);"string"===typeof b?(d=a[b],null==d&&(d=a[c.camelCase(b)])):d=a;return d}}}function Va(a,b,d){if(c.acceptData(a)){var e,f,g=a.nodeType,h=g?c.cache:a,k=g?a[c.expando]:c.expando;if(h[k]){if(b&&(e=d?h[k]:h[k].data)){c.isArray(b)?b=b.concat(c.map(b,c.camelCase)):b in e?b=[b]:(b=c.camelCase(b),b=b in e?[b]:b.split(" "));for(f=b.length;f--;)delete e[b[f]];if(d?
!ya(e):!c.isEmptyObject(e))return}if(d||(delete h[k].data,ya(h[k])))g?c.cleanData([a],!0):c.support.deleteExpando||h!=h.window?delete h[k]:h[k]=null}}}function Wa(a,b,d){if(d===n&&1===a.nodeType)if(d="data-"+b.replace(Vb,"-$1").toLowerCase(),d=a.getAttribute(d),"string"===typeof d){try{d="true"===d?!0:"false"===d?!1:"null"===d?null:+d+""===d?+d:Wb.test(d)?c.parseJSON(d):d}catch(e){}c.data(a,b,d)}else d=n;return d}function ya(a){for(var b in a)if(("data"!==b||!c.isEmptyObject(a[b]))&&"toJSON"!==b)return!1;
return!0}function na(){return!0}function T(){return!1}function Xa(){try{return p.activeElement}catch(a){}}function Ya(a,b){do a=a[b];while(a&&1!==a.nodeType);return a}function za(a,b,d){if(c.isFunction(b))return c.grep(a,function(a,c){return!!b.call(a,c,a)!==d});if(b.nodeType)return c.grep(a,function(a){return a===b!==d});if("string"===typeof b){if(Xb.test(b))return c.filter(b,a,d);b=c.filter(b,a)}return c.grep(a,function(a){return 0<=c.inArray(a,b)!==d})}function Za(a){var b=$a.split("|");a=a.createDocumentFragment();
if(a.createElement)for(;b.length;)a.createElement(b.pop());return a}function ab(a,b){return c.nodeName(a,"table")&&c.nodeName(1===b.nodeType?b:b.firstChild,"tr")?a.getElementsByTagName("tbody")[0]||a.appendChild(a.ownerDocument.createElement("tbody")):a}function bb(a){a.type=(null!==c.find.attr(a,"type"))+"/"+a.type;return a}function cb(a){var b=Yb.exec(a.type);b?a.type=b[1]:a.removeAttribute("type");return a}function Aa(a,b){for(var d,e=0;null!=(d=a[e]);e++)c._data(d,"globalEval",!b||c._data(b[e],
"globalEval"))}function db(a,b){if(1===b.nodeType&&c.hasData(a)){var d,e,f;e=c._data(a);var g=c._data(b,e),h=e.events;if(h)for(d in delete g.handle,g.events={},h)for(e=0,f=h[d].length;e<f;e++)c.event.add(b,d,h[d][e]);g.data&&(g.data=c.extend({},g.data))}}function C(a,b){var d,e,f=0,g=typeof a.getElementsByTagName!==A?a.getElementsByTagName(b||"*"):typeof a.querySelectorAll!==A?a.querySelectorAll(b||"*"):n;if(!g)for(g=[],d=a.childNodes||a;null!=(e=d[f]);f++)!b||c.nodeName(e,b)?g.push(e):c.merge(g,
C(e,b));return b===n||b&&c.nodeName(a,b)?c.merge([a],g):g}function Zb(a){Ba.test(a.type)&&(a.defaultChecked=a.checked)}function eb(a,b){if(b in a)return b;for(var d=b.charAt(0).toUpperCase()+b.slice(1),c=b,f=fb.length;f--;)if(b=fb[f]+d,b in a)return b;return c}function ha(a,b){a=b||a;return"none"===c.css(a,"display")||!c.contains(a.ownerDocument,a)}function gb(a,b){for(var d,e,f,g=[],h=0,k=a.length;h<k;h++)e=a[h],e.style&&(g[h]=c._data(e,"olddisplay"),d=e.style.display,b?(g[h]||"none"!==d||(e.style.display=
""),""===e.style.display&&ha(e)&&(g[h]=c._data(e,"olddisplay",hb(e.nodeName)))):g[h]||(f=ha(e),(d&&"none"!==d||!f)&&c._data(e,"olddisplay",f?d:c.css(e,"display"))));for(h=0;h<k;h++)e=a[h],!e.style||b&&"none"!==e.style.display&&""!==e.style.display||(e.style.display=b?g[h]||"":"none");return a}function ib(a,b,d){return(a=$b.exec(b))?Math.max(0,a[1]-(d||0))+(a[2]||"px"):b}function jb(a,b,d,e,f){b=d===(e?"border":"content")?4:"width"===b?1:0;for(var g=0;4>b;b+=2)"margin"===d&&(g+=c.css(a,d+R[b],!0,f)),
e?("content"===d&&(g-=c.css(a,"padding"+R[b],!0,f)),"margin"!==d&&(g-=c.css(a,"border"+R[b]+"Width",!0,f))):(g+=c.css(a,"padding"+R[b],!0,f),"padding"!==d&&(g+=c.css(a,"border"+R[b]+"Width",!0,f)));return g}function kb(a,b,d){var e=!0,f="width"===b?a.offsetWidth:a.offsetHeight,g=I(a),h=c.support.boxSizing&&"border-box"===c.css(a,"boxSizing",!1,g);if(0>=f||null==f){f=N(a,b,g);if(0>f||null==f)f=a.style[b];if(oa.test(f))return f;e=h&&(c.support.boxSizingReliable||f===a.style[b]);f=parseFloat(f)||0}return f+
jb(a,b,d||(h?"border":"content"),e,g)+"px"}function hb(a){var b=p,d=lb[a];d||(d=mb(a,b),"none"!==d&&d||(ia=(ia||c("<iframe frameborder='0' width='0' height='0'/>").css("cssText","display:block !important")).appendTo(b.documentElement),b=(ia[0].contentWindow||ia[0].contentDocument).document,b.write("<!doctype html><html><body>"),b.close(),d=mb(a,b),ia.detach()),lb[a]=d);return d}function mb(a,b){var d=c(b.createElement(a)).appendTo(b.body),e=c.css(d[0],"display");d.remove();return e}function Ca(a,
b,d,e){var f;if(c.isArray(b))c.each(b,function(b,c){d||ac.test(a)?e(a,c):Ca(a+"["+("object"===typeof c?b:"")+"]",c,d,e)});else if(d||"object"!==c.type(b))e(a,b);else for(f in b)Ca(a+"["+f+"]",b[f],d,e)}function nb(a){return function(b,d){"string"!==typeof b&&(d=b,b="*");var e,f=0,g=b.toLowerCase().match(F)||[];if(c.isFunction(d))for(;e=g[f++];)"+"===e[0]?(e=e.slice(1)||"*",(a[e]=a[e]||[]).unshift(d)):(a[e]=a[e]||[]).push(d)}}function ob(a,b,d,e){function f(k){var l;g[k]=!0;c.each(a[k]||[],function(a,
c){var k=c(b,d,e);if("string"===typeof k&&!h&&!g[k])return b.dataTypes.unshift(k),f(k),!1;if(h)return!(l=k)});return l}var g={},h=a===Da;return f(b.dataTypes[0])||!g["*"]&&f("*")}function Ea(a,b){var d,e,f=c.ajaxSettings.flatOptions||{};for(e in b)b[e]!==n&&((f[e]?a:d||(d={}))[e]=b[e]);d&&c.extend(!0,a,d);return a}function pb(){try{return new t.XMLHttpRequest}catch(a){}}function qb(){setTimeout(function(){U=n});return U=c.now()}function rb(a,b,c){for(var e,f=(V[b]||[]).concat(V["*"]),g=0,h=f.length;g<
h;g++)if(e=f[g].call(c,b,a))return e}function sb(a,b,d){var e,f=0,g=W.length,h=c.Deferred().always(function(){delete k.elem}),k=function(){if(e)return!1;for(var b=U||qb(),b=Math.max(0,l.startTime+l.duration-b),c=1-(b/l.duration||0),d=0,f=l.tweens.length;d<f;d++)l.tweens[d].run(c);h.notifyWith(a,[l,c,b]);if(1>c&&f)return b;h.resolveWith(a,[l]);return!1},l=h.promise({elem:a,props:c.extend({},b),opts:c.extend(!0,{specialEasing:{}},d),originalProperties:b,originalOptions:d,startTime:U||qb(),duration:d.duration,
tweens:[],createTween:function(b,d){var e=c.Tween(a,l.opts,b,d,l.opts.specialEasing[b]||l.opts.easing);l.tweens.push(e);return e},stop:function(b){var c=0,d=b?l.tweens.length:0;if(e)return this;for(e=!0;c<d;c++)l.tweens[c].run(1);b?h.resolveWith(a,[l,b]):h.rejectWith(a,[l,b]);return this}});d=l.props;for(bc(d,l.opts.specialEasing);f<g;f++)if(b=W[f].call(l,a,d,l.opts))return b;c.map(d,rb,l);c.isFunction(l.opts.start)&&l.opts.start.call(a,l);c.fx.timer(c.extend(k,{elem:a,anim:l,queue:l.opts.queue}));
return l.progress(l.opts.progress).done(l.opts.done,l.opts.complete).fail(l.opts.fail).always(l.opts.always)}function bc(a,b){var d,e,f,g,h;for(d in a)if(e=c.camelCase(d),f=b[e],g=a[d],c.isArray(g)&&(f=g[1],g=a[d]=g[0]),d!==e&&(a[e]=g,delete a[d]),(h=c.cssHooks[e])&&"expand"in h)for(d in g=h.expand(g),delete a[e],g)d in a||(a[d]=g[d],b[d]=f);else b[e]=f}function G(a,b,c,e,f){return new G.prototype.init(a,b,c,e,f)}function ca(a,b){var c,e={height:a},f=0;for(b=b?1:0;4>f;f+=2-b)c=R[f],e["margin"+c]=
e["padding"+c]=a;b&&(e.opacity=e.width=a);return e}function tb(a){return c.isWindow(a)?a:9===a.nodeType?a.defaultView||a.parentWindow:!1}var pa,ub,A=typeof n,cc=t.location,p=t.document,vb=p.documentElement,dc=t.jQuery,ec=t.$,qa={},ba=[],wb=ba.concat,Fa=ba.push,D=ba.slice,xb=ba.indexOf,fc=qa.toString,X=qa.hasOwnProperty,Ga="1.10.2".trim,c=function(a,b){return new c.fn.init(a,b,ub)},ra=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,F=/\S+/g,gc=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,hc=/^(?:\s*(<[\w\W]+>)[^>]*|#([\w-]*))$/,
yb=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,ic=/^[\],:{}\s]*$/,jc=/(?:^|:|,)(?:\s*\[)+/g,kc=/\\(?:["\\\/bfnrt]|u[\da-fA-F]{4})/g,lc=/"[^"\\\r\n]*"|true|false|null|-?(?:\d+\.|)\d+(?:[eE][+-]?\d+|)/g,mc=/^-ms-/,nc=/-([\da-z])/gi,oc=function(a,b){return b.toUpperCase()},O=function(a){if(p.addEventListener||"load"===a.type||"complete"===p.readyState)zb(),c.ready()},zb=function(){p.addEventListener?(p.removeEventListener("DOMContentLoaded",O,!1),t.removeEventListener("load",O,!1)):(p.detachEvent("onreadystatechange",
O),t.detachEvent("onload",O))};c.fn=c.prototype={jquery:"1.10.2",constructor:c,init:function(a,b,d){var e;if(!a)return this;if("string"===typeof a){e="<"===a.charAt(0)&&">"===a.charAt(a.length-1)&&3<=a.length?[null,a,null]:hc.exec(a);if(!e||!e[1]&&b)return!b||b.jquery?(b||d).find(a):this.constructor(b).find(a);if(e[1]){if(b=b instanceof c?b[0]:b,c.merge(this,c.parseHTML(e[1],b&&b.nodeType?b.ownerDocument||b:p,!0)),yb.test(e[1])&&c.isPlainObject(b))for(e in b)if(c.isFunction(this[e]))this[e](b[e]);
else this.attr(e,b[e])}else{if((b=p.getElementById(e[2]))&&b.parentNode){if(b.id!==e[2])return d.find(a);this.length=1;this[0]=b}this.context=p;this.selector=a}return this}if(a.nodeType)return this.context=this[0]=a,this.length=1,this;if(c.isFunction(a))return d.ready(a);a.selector!==n&&(this.selector=a.selector,this.context=a.context);return c.makeArray(a,this)},selector:"",length:0,toArray:function(){return D.call(this)},get:function(a){return null==a?this.toArray():0>a?this[this.length+a]:this[a]},
pushStack:function(a){a=c.merge(this.constructor(),a);a.prevObject=this;a.context=this.context;return a},each:function(a,b){return c.each(this,a,b)},ready:function(a){c.ready.promise().done(a);return this},slice:function(){return this.pushStack(D.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},eq:function(a){var b=this.length;a=+a+(0>a?b:0);return this.pushStack(0<=a&&a<b?[this[a]]:[])},map:function(a){return this.pushStack(c.map(this,function(b,c){return a.call(b,
c,b)}))},end:function(){return this.prevObject||this.constructor(null)},push:Fa,sort:[].sort,splice:[].splice};c.fn.init.prototype=c.fn;c.extend=c.fn.extend=function(){var a,b,d,e,f,g=arguments[0]||{},h=1,k=arguments.length,l=!1;"boolean"===typeof g&&(l=g,g=arguments[1]||{},h=2);"object"===typeof g||c.isFunction(g)||(g={});for(k===h&&(g=this,--h);h<k;h++)if(null!=(f=arguments[h]))for(e in f)a=g[e],d=f[e],g!==d&&(l&&d&&(c.isPlainObject(d)||(b=c.isArray(d)))?(b?(b=!1,a=a&&c.isArray(a)?a:[]):a=a&&c.isPlainObject(a)?
a:{},g[e]=c.extend(l,a,d)):d!==n&&(g[e]=d));return g};c.extend({expando:"jQuery"+("1.10.2"+Math.random()).replace(/\D/g,""),noConflict:function(a){t.$===c&&(t.$=ec);a&&t.jQuery===c&&(t.jQuery=dc);return c},isReady:!1,readyWait:1,holdReady:function(a){a?c.readyWait++:c.ready(!0)},ready:function(a){if(!0===a?!--c.readyWait:!c.isReady){if(!p.body)return setTimeout(c.ready);c.isReady=!0;!0!==a&&0<--c.readyWait||(pa.resolveWith(p,[c]),c.fn.trigger&&c(p).trigger("ready").off("ready"))}},isFunction:function(a){return"function"===
c.type(a)},isArray:Array.isArray||function(a){return"array"===c.type(a)},isWindow:function(a){return null!=a&&a==a.window},isNumeric:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},type:function(a){return null==a?String(a):"object"===typeof a||"function"===typeof a?qa[fc.call(a)]||"object":typeof a},isPlainObject:function(a){var b;if(!a||"object"!==c.type(a)||a.nodeType||c.isWindow(a))return!1;try{if(a.constructor&&!X.call(a,"constructor")&&!X.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(d){return!1}if(c.support.ownLast)for(b in a)return X.call(a,
b);for(b in a);return b===n||X.call(a,b)},isEmptyObject:function(a){for(var b in a)return!1;return!0},error:function(a){throw Error(a);},parseHTML:function(a,b,d){if(!a||"string"!==typeof a)return null;"boolean"===typeof b&&(d=b,b=!1);b=b||p;var e=yb.exec(a);d=!d&&[];if(e)return[b.createElement(e[1])];e=c.buildFragment([a],b,d);d&&c(d).remove();return c.merge([],e.childNodes)},parseJSON:function(a){if(t.JSON&&t.JSON.parse)return t.JSON.parse(a);if(null===a)return a;if("string"===typeof a&&(a=c.trim(a))&&
ic.test(a.replace(kc,"@").replace(lc,"]").replace(jc,"")))return(new Function("return "+a))();c.error("Invalid JSON: "+a)},parseXML:function(a){var b,d;if(!a||"string"!==typeof a)return null;try{t.DOMParser?(d=new DOMParser,b=d.parseFromString(a,"text/xml")):(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",b.loadXML(a))}catch(e){b=n}b&&b.documentElement&&!b.getElementsByTagName("parsererror").length||c.error("Invalid XML: "+a);return b},noop:function(){},globalEval:function(a){a&&c.trim(a)&&
(t.execScript||function(a){t.eval.call(t,a)})(a)},camelCase:function(a){return a.replace(mc,"ms-").replace(nc,oc)},nodeName:function(a,b){return a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()},each:function(a,b,c){var e,f=0,g=a.length;e=xa(a);if(c)if(e)for(;f<g&&(e=b.apply(a[f],c),!1!==e);f++);else for(f in a){if(e=b.apply(a[f],c),!1===e)break}else if(e)for(;f<g&&(e=b.call(a[f],f,a[f]),!1!==e);f++);else for(f in a)if(e=b.call(a[f],f,a[f]),!1===e)break;return a},trim:Ga&&!Ga.call("\ufeff\u00a0")?
function(a){return null==a?"":Ga.call(a)}:function(a){return null==a?"":(a+"").replace(gc,"")},makeArray:function(a,b){var d=b||[];null!=a&&(xa(Object(a))?c.merge(d,"string"===typeof a?[a]:a):Fa.call(d,a));return d},inArray:function(a,b,c){var e;if(b){if(xb)return xb.call(b,a,c);e=b.length;for(c=c?0>c?Math.max(0,e+c):c:0;c<e;c++)if(c in b&&b[c]===a)return c}return-1},merge:function(a,b){var c=b.length,e=a.length,f=0;if("number"===typeof c)for(;f<c;f++)a[e++]=b[f];else for(;b[f]!==n;)a[e++]=b[f++];
a.length=e;return a},grep:function(a,b,c){var e,f=[],g=0,h=a.length;for(c=!!c;g<h;g++)e=!!b(a[g],g),c!==e&&f.push(a[g]);return f},map:function(a,b,c){var e,f=0,g=a.length,h=[];if(xa(a))for(;f<g;f++)e=b(a[f],f,c),null!=e&&(h[h.length]=e);else for(f in a)e=b(a[f],f,c),null!=e&&(h[h.length]=e);return wb.apply([],h)},guid:1,proxy:function(a,b){var d,e;"string"===typeof b&&(e=a[b],b=a,a=e);if(!c.isFunction(a))return n;d=D.call(arguments,2);e=function(){return a.apply(b||this,d.concat(D.call(arguments)))};
e.guid=a.guid=a.guid||c.guid++;return e},access:function(a,b,d,e,f,g,h){var k=0,l=a.length,q=null==d;if("object"===c.type(d))for(k in f=!0,d)c.access(a,b,k,d[k],!0,g,h);else if(e!==n&&(f=!0,c.isFunction(e)||(h=!0),q&&(h?(b.call(a,e),b=null):(q=b,b=function(a,b,d){return q.call(c(a),d)})),b))for(;k<l;k++)b(a[k],d,h?e:e.call(a[k],k,b(a[k],d)));return f?a:q?b.call(a):l?b(a[0],d):g},now:function(){return(new Date).getTime()},swap:function(a,b,c,e){var f,g={};for(f in b)g[f]=a.style[f],a.style[f]=b[f];
c=c.apply(a,e||[]);for(f in b)a.style[f]=g[f];return c}});c.ready.promise=function(a){if(!pa)if(pa=c.Deferred(),"complete"===p.readyState)setTimeout(c.ready);else if(p.addEventListener)p.addEventListener("DOMContentLoaded",O,!1),t.addEventListener("load",O,!1);else{p.attachEvent("onreadystatechange",O);t.attachEvent("onload",O);var b=!1;try{b=null==t.frameElement&&p.documentElement}catch(d){}b&&b.doScroll&&function f(){if(!c.isReady){try{b.doScroll("left")}catch(a){return setTimeout(f,50)}zb();c.ready()}}()}return pa.promise(a)};
c.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),function(a,b){qa["[object "+b+"]"]=b.toLowerCase()});ub=c(p);(function(a,b){function d(a,b,c,d){var e,f,g,h,k;(b?b.ownerDocument||b:Y)!==y&&ja(b);b=b||y;c=c||[];if(!a||"string"!==typeof a)return c;if(1!==(h=b.nodeType)&&9!==h)return[];if(H&&!d){if(e=pa.exec(a))if(g=e[1])if(9===h)if((f=b.getElementById(g))&&f.parentNode){if(f.id===g)return c.push(f),c}else return c;else{if(b.ownerDocument&&(f=b.ownerDocument.getElementById(g))&&
ta(b,f)&&f.id===g)return c.push(f),c}else{if(e[2])return da.apply(c,b.getElementsByTagName(a)),c;if((g=e[3])&&r.getElementsByClassName&&b.getElementsByClassName)return da.apply(c,b.getElementsByClassName(g)),c}if(r.qsa&&(!K||!K.test(a))){f=e=x;g=b;k=9===h&&a;if(1===h&&"object"!==b.nodeName.toLowerCase()){h=n(a);(e=b.getAttribute("id"))?f=e.replace(sa,"\\$&"):b.setAttribute("id",f);f="[id='"+f+"'] ";for(g=h.length;g--;)h[g]=f+L(h[g]);g=V.test(a)&&b.parentNode||b;k=h.join(",")}if(k)try{return da.apply(c,
g.querySelectorAll(k)),c}catch(l){}finally{e||b.removeAttribute("id")}}}var m;a:{a=a.replace(Q,"$1");f=n(a);if(!d&&1===f.length){e=f[0]=f[0].slice(0);if(2<e.length&&"ID"===(m=e[0]).type&&r.getById&&9===b.nodeType&&H&&v.relative[e[1].type]){b=(v.find.ID(m.matches[0].replace(ea,fa),b)||[])[0];if(!b){m=c;break a}a=a.slice(e.shift().value.length)}for(h=W.needsContext.test(a)?0:e.length;h--;){m=e[h];if(v.relative[g=m.type])break;if(g=v.find[g])if(d=g(m.matches[0].replace(ea,fa),V.test(e[0].type)&&b.parentNode||
b)){e.splice(h,1);a=d.length&&L(e);if(!a){da.apply(c,d);m=c;break a}break}}}Ia(a,f)(d,b,!H,c,V.test(a));m=c}return m}function e(){function a(c,d){b.push(c+=" ")>v.cacheLength&&delete a[b.shift()];return a[c]=d}var b=[];return a}function f(a){a[x]=!0;return a}function g(a){var b=y.createElement("div");try{return!!a(b)}catch(c){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function h(a,b){for(var c=a.split("|"),d=a.length;d--;)v.attrHandle[c[d]]=b}function k(a,b){var c=b&&a,d=c&&1===a.nodeType&&
1===b.nodeType&&(~b.sourceIndex||-2147483648)-(~a.sourceIndex||-2147483648);if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function l(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function q(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function u(a){return f(function(b){b=+b;return f(function(c,d){for(var e,f=a([],c.length,b),g=f.length;g--;)c[e=f[g]]&&(c[e]=!(d[e]=c[e]))})})}function m(){}
function n(a,b){var c,e,f,g,h,k,m;if(h=P[a+" "])return b?0:h.slice(0);h=a;k=[];for(m=v.preFilter;h;){if(!c||(e=ha.exec(h)))e&&(h=h.slice(e[0].length)||h),k.push(f=[]);c=!1;if(e=ia.exec(h))c=e.shift(),f.push({value:c,type:e[0].replace(Q," ")}),h=h.slice(c.length);for(g in v.filter)!(e=W[g].exec(h))||m[g]&&!(e=m[g](e))||(c=e.shift(),f.push({value:c,type:g,matches:e}),h=h.slice(c.length));if(!c)break}return b?h.length:h?d.error(a):P(a,k).slice(0)}function L(a){for(var b=0,c=a.length,d="";b<c;b++)d+=
a[b].value;return d}function p(a,b,c){var d=b.dir,e=c&&"parentNode"===d,f=qc++;return b.first?function(b,c,f){for(;b=b[d];)if(1===b.nodeType||e)return a(b,c,f)}:function(b,c,g){var h,k,Ha,m=E+" "+f;if(g)for(;b=b[d];){if((1===b.nodeType||e)&&a(b,c,g))return!0}else for(;b=b[d];)if(1===b.nodeType||e)if(Ha=b[x]||(b[x]={}),(k=Ha[d])&&k[0]===m){if(!0===(h=k[1])||h===F)return!0===h}else if(k=Ha[d]=[m],k[1]=a(b,c,g)||F,!0===k[1])return!0}}function t(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,
c,d))return!1;return!0}:a[0]}function va(a,b,c,d,e){for(var f,g=[],h=0,k=a.length,m=null!=b;h<k;h++)if(f=a[h])if(!c||c(f,d,e))g.push(f),m&&b.push(h);return g}function C(a,b,c,e,g,h){e&&!e[x]&&(e=C(e));g&&!g[x]&&(g=C(g,h));return f(function(f,h,k,m){var l,q,u=[],n=[],w=h.length,v;if(!(v=f)){v=b||"*";for(var r=k.nodeType?[k]:k,L=[],p=0,t=r.length;p<t;p++)d(v,r[p],L);v=L}v=!a||!f&&b?v:va(v,u,a,k,m);r=c?g||(f?a:w||e)?[]:h:v;c&&c(v,r,k,m);if(e)for(l=va(r,n),e(l,[],k,m),k=l.length;k--;)if(q=l[k])r[n[k]]=
!(v[n[k]]=q);if(f){if(g||a){if(g){l=[];for(k=r.length;k--;)(q=r[k])&&l.push(v[k]=q);g(null,r=[],l,m)}for(k=r.length;k--;)(q=r[k])&&-1<(l=g?ka.call(f,q):u[k])&&(f[l]=!(h[l]=q))}}else r=va(r===h?r.splice(w,r.length):r),g?g(null,h,r,m):da.apply(h,r)})}function G(a){var b,c,d,e=a.length,f=v.relative[a[0].type];c=f||v.relative[" "];for(var g=f?1:0,h=p(function(a){return a===b},c,!0),k=p(function(a){return-1<ka.call(b,a)},c,!0),m=[function(a,c,d){return!f&&(d||c!==A)||((b=c).nodeType?h(a,c,d):k(a,c,d))}];g<
e;g++)if(c=v.relative[a[g].type])m=[p(t(m),c)];else{c=v.filter[a[g].type].apply(null,a[g].matches);if(c[x]){for(d=++g;d<e&&!v.relative[a[d].type];d++);return C(1<g&&t(m),1<g&&L(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(Q,"$1"),c,g<d&&G(a.slice(g,d)),d<e&&G(a=a.slice(d)),d<e&&L(a))}m.push(c)}return t(m)}function rc(a,b){var c=0,e=0<b.length,g=0<a.length,h=function(f,h,k,m,l){var q,u,n=[],r=0,w="0",p=f&&[],L=null!=l,t=A,pc=f||g&&v.find.TAG("*",l&&h.parentNode||h),x=E+=null==t?
1:Math.random()||.1;for(L&&(A=h!==y&&h,F=c);null!=(l=pc[w]);w++){if(g&&l){for(q=0;u=a[q++];)if(u(l,h,k)){m.push(l);break}L&&(E=x,F=++c)}e&&((l=!u&&l)&&r--,f&&p.push(l))}r+=w;if(e&&w!==r){for(q=0;u=b[q++];)u(p,n,h,k);if(f){if(0<r)for(;w--;)p[w]||n[w]||(n[w]=aa.call(m));n=va(n)}da.apply(m,n);L&&!f&&0<n.length&&1<r+b.length&&d.uniqueSort(m)}L&&(E=x,A=t);return p};return e?f(h):h}var z,r,F,v,wa,Ab,Ia,A,la,ja,y,J,H,K,M,B,ta,x="sizzle"+-new Date,Y=a.document,E=0,qc=0,O=e(),P=e(),R=e(),I=!1,N=function(a,
b){a===b&&(I=!0);return 0},D=typeof b,Z={}.hasOwnProperty,ga=[],aa=ga.pop,ba=ga.push,da=ga.push,T=ga.slice,ka=ga.indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(this[b]===a)return b;return-1},U="(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w#"),X="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+U+")|)|)[\\x20\\t\\r\\n\\f]*\\]",S=":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\(((['\"])((?:\\\\.|[^\\\\])*?)\\3|((?:\\\\.|[^\\\\()[\\]]|"+
X.replace(3,8)+")*)|.*)\\)|)",Q=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),ha=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,ia=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,V=/[\x20\t\r\n\f]*[+~]/,ma=RegExp("=[\\x20\\t\\r\\n\\f]*([^\\]'\"]*)[\\x20\\t\\r\\n\\f]*\\]","g"),na=new RegExp(S),oa=new RegExp("^"+U+"$"),W={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:new RegExp("^("+"(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w*")+
")"),ATTR:new RegExp("^"+X),PSEUDO:new RegExp("^"+S),CHILD:/^:(only|first|last|nth|nth-last)-(child|of-type)(?:\([\x20\t\r\n\f]*(even|odd|(([+-]|)(\d*)n|)[\x20\t\r\n\f]*(?:([+-]|)[\x20\t\r\n\f]*(\d+)|))[\x20\t\r\n\f]*\)|)/i,bool:/^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$/i,needsContext:/^[\x20\t\r\n\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\([\x20\t\r\n\f]*((?:-\d)?\d*)[\x20\t\r\n\f]*\)|)(?=[^-]|$)/i},ca=
/^[^{]+\{\s*\[native \w/,pa=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,qa=/^(?:input|select|textarea|button)$/i,ra=/^h\d$/i,sa=/'|\\/g,ea=RegExp("\\\\([\\da-f]{1,6}[\\x20\\t\\r\\n\\f]?|([\\x20\\t\\r\\n\\f])|.)","ig"),fa=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)};try{da.apply(ga=T.call(Y.childNodes),Y.childNodes),ga[Y.childNodes.length].nodeType}catch(ua){da={apply:ga.length?function(a,b){ba.apply(a,T.call(b))}:function(a,
b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}Ab=d.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};r=d.support={};ja=d.setDocument=function(a){var b=a?a.ownerDocument||a:Y;a=b.defaultView;if(b===y||9!==b.nodeType||!b.documentElement)return y;y=b;J=b.documentElement;H=!Ab(b);a&&a.attachEvent&&a!==a.top&&a.attachEvent("onbeforeunload",function(){ja()});r.attributes=g(function(a){a.className="i";return!a.getAttribute("className")});r.getElementsByTagName=
g(function(a){a.appendChild(b.createComment(""));return!a.getElementsByTagName("*").length});r.getElementsByClassName=g(function(a){a.innerHTML="<div class='a'></div><div class='a i'></div>";a.firstChild.className="i";return 2===a.getElementsByClassName("i").length});r.getById=g(function(a){J.appendChild(a).id=x;return!b.getElementsByName||!b.getElementsByName(x).length});r.getById?(v.find.ID=function(a,b){if(typeof b.getElementById!==D&&H){var c=b.getElementById(a);return c&&c.parentNode?[c]:[]}},
v.filter.ID=function(a){var b=a.replace(ea,fa);return function(a){return a.getAttribute("id")===b}}):(delete v.find.ID,v.filter.ID=function(a){var b=a.replace(ea,fa);return function(a){return(a=typeof a.getAttributeNode!==D&&a.getAttributeNode("id"))&&a.value===b}});v.find.TAG=r.getElementsByTagName?function(a,b){if(typeof b.getElementsByTagName!==D)return b.getElementsByTagName(a)}:function(a,b){var c,d=[],e=0,f=b.getElementsByTagName(a);if("*"===a){for(;c=f[e++];)1===c.nodeType&&d.push(c);return d}return f};
v.find.CLASS=r.getElementsByClassName&&function(a,b){if(typeof b.getElementsByClassName!==D&&H)return b.getElementsByClassName(a)};M=[];K=[];if(r.qsa=ca.test(b.querySelectorAll))g(function(a){a.innerHTML="<select><option selected=''></option></select>";a.querySelectorAll("[selected]").length||K.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");a.querySelectorAll(":checked").length||K.push(":checked")}),
g(function(a){var c=b.createElement("input");c.setAttribute("type","hidden");a.appendChild(c).setAttribute("t","");a.querySelectorAll("[t^='']").length&&K.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll(":enabled").length||K.push(":enabled",":disabled");a.querySelectorAll("*,:x");K.push(",.*:")});(r.matchesSelector=ca.test(B=J.webkitMatchesSelector||J.mozMatchesSelector||J.oMatchesSelector||J.msMatchesSelector))&&g(function(a){r.disconnectedMatch=B.call(a,"div");B.call(a,"[s!='']:x");
M.push("!=",S)});K=K.length&&new RegExp(K.join("|"));M=M.length&&new RegExp(M.join("|"));ta=ca.test(J.contains)||J.compareDocumentPosition?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!!(d&&1===d.nodeType&&(c.contains?c.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};N=J.compareDocumentPosition?function(a,c){if(a===c)return I=!0,0;var d=c.compareDocumentPosition&&
a.compareDocumentPosition&&a.compareDocumentPosition(c);return d?d&1||!r.sortDetached&&c.compareDocumentPosition(a)===d?a===b||ta(Y,a)?-1:c===b||ta(Y,c)?1:la?ka.call(la,a)-ka.call(la,c):0:d&4?-1:1:a.compareDocumentPosition?-1:1}:function(a,c){var d,e=0;d=a.parentNode;var f=c.parentNode,g=[a],h=[c];if(a===c)return I=!0,0;if(!d||!f)return a===b?-1:c===b?1:d?-1:f?1:la?ka.call(la,a)-ka.call(la,c):0;if(d===f)return k(a,c);for(d=a;d=d.parentNode;)g.unshift(d);for(d=c;d=d.parentNode;)h.unshift(d);for(;g[e]===
h[e];)e++;return e?k(g[e],h[e]):g[e]===Y?-1:h[e]===Y?1:0};return b};d.matches=function(a,b){return d(a,null,null,b)};d.matchesSelector=function(a,b){(a.ownerDocument||a)!==y&&ja(a);b=b.replace(ma,"='$1']");if(!(!r.matchesSelector||!H||M&&M.test(b)||K&&K.test(b)))try{var c=B.call(a,b);if(c||r.disconnectedMatch||a.document&&11!==a.document.nodeType)return c}catch(e){}return 0<d(b,y,null,[a]).length};d.contains=function(a,b){(a.ownerDocument||a)!==y&&ja(a);return ta(a,b)};d.attr=function(a,c){(a.ownerDocument||
a)!==y&&ja(a);var d=v.attrHandle[c.toLowerCase()],d=d&&Z.call(v.attrHandle,c.toLowerCase())?d(a,c,!H):b;return d===b?r.attributes||!H?a.getAttribute(c):(d=a.getAttributeNode(c))&&d.specified?d.value:null:d};d.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};d.uniqueSort=function(a){var b,c=[],d=0,e=0;I=!r.detectDuplicates;la=!r.sortStable&&a.slice(0);a.sort(N);if(I){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],1)}return a};wa=d.getText=function(a){var b,
c="",d=0;b=a.nodeType;if(!b)for(;b=a[d];d++)c+=wa(b);else if(1===b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=wa(a)}else if(3===b||4===b)return a.nodeValue;return c};v=d.selectors={cacheLength:50,createPseudo:f,match:W,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(ea,fa);a[3]=(a[4]||
a[5]||"").replace(ea,fa);"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||d.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&d.error(a[0]);return a},PSEUDO:function(a){var c,d=!a[5]&&a[2];if(W.CHILD.test(a[0]))return null;a[3]&&a[4]!==b?a[2]=a[4]:d&&na.test(d)&&(c=n(d,!0))&&(c=d.indexOf(")",d.length-c)-d.length)&&(a[0]=a[0].slice(0,c),a[2]=d.slice(0,c));return a.slice(0,
3)}},filter:{TAG:function(a){var b=a.replace(ea,fa).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=O[a+" "];return b||(b=new RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&O(a,function(a){return b.test("string"===typeof a.className&&a.className||typeof a.getAttribute!==D&&a.getAttribute("class")||"")})},ATTR:function(a,b,c){return function(e){e=d.attr(e,a);if(null==e)return"!="===b;if(!b)return!0;
e+="";return"="===b?e===c:"!="===b?e!==c:"^="===b?c&&0===e.indexOf(c):"*="===b?c&&-1<e.indexOf(c):"$="===b?c&&e.slice(-c.length)===c:"~="===b?-1<(" "+e+" ").indexOf(c):"|="===b?e===c||e.slice(0,c.length+1)===c+"-":!1}},CHILD:function(a,b,c,d,e){var f="nth"!==a.slice(0,3),g="last"!==a.slice(-4),h="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,k){var m,l,q,u,n;c=f!==g?"nextSibling":"previousSibling";var r=b.parentNode,w=h&&b.nodeName.toLowerCase();k=!k&&!h;if(r){if(f){for(;c;){for(l=
b;l=l[c];)if(h?l.nodeName.toLowerCase()===w:1===l.nodeType)return!1;n=c="only"===a&&!n&&"nextSibling"}return!0}n=[g?r.firstChild:r.lastChild];if(g&&k)for(k=r[x]||(r[x]={}),m=k[a]||[],u=m[0]===E&&m[1],q=m[0]===E&&m[2],l=u&&r.childNodes[u];l=++u&&l&&l[c]||(q=u=0)||n.pop();){if(1===l.nodeType&&++q&&l===b){k[a]=[E,u,q];break}}else if(k&&(m=(b[x]||(b[x]={}))[a])&&m[0]===E)q=m[1];else for(;(l=++u&&l&&l[c]||(q=u=0)||n.pop())&&((h?l.nodeName.toLowerCase()!==w:1!==l.nodeType)||!++q||(k&&((l[x]||(l[x]={}))[a]=
[E,q]),l!==b)););q-=e;return q===d||0===q%d&&0<=q/d}}},PSEUDO:function(a,b){var c,e=v.pseudos[a]||v.setFilters[a.toLowerCase()]||d.error("unsupported pseudo: "+a);return e[x]?e(b):1<e.length?(c=[a,a,"",b],v.setFilters.hasOwnProperty(a.toLowerCase())?f(function(a,c){for(var d,f=e(a,b),g=f.length;g--;)d=ka.call(a,f[g]),a[d]=!(c[d]=f[g])}):function(a){return e(a,0,c)}):e}},pseudos:{not:f(function(a){var b=[],c=[],d=Ia(a.replace(Q,"$1"));return d[x]?f(function(a,b,c,e){e=d(a,null,e,[]);for(var f=a.length;f--;)if(c=
e[f])a[f]=!(b[f]=c)}):function(a,e,f){b[0]=a;d(b,null,f,c);return!c.pop()}}),has:f(function(a){return function(b){return 0<d(a,b).length}}),contains:f(function(a){return function(b){return-1<(b.textContent||b.innerText||wa(b)).indexOf(a)}}),lang:f(function(a){oa.test(a||"")||d.error("unsupported lang: "+a);a=a.replace(ea,fa).toLowerCase();return function(b){var c;do if(c=H?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&
1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===J},focus:function(a){return a===y.activeElement&&(!y.hasFocus||y.hasFocus())&&!!(a.type||a.href||~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;
return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if("@"<a.nodeName||3===a.nodeType||4===a.nodeType)return!1;return!0},parent:function(a){return!v.pseudos.empty(a)},header:function(a){return ra.test(a.nodeName)},input:function(a){return qa.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||
b.toLowerCase()===a.type)},first:u(function(){return[0]}),last:u(function(a,b){return[b-1]}),eq:u(function(a,b,c){return[0>c?c+b:c]}),even:u(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:u(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:u(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:u(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};v.pseudos.nth=v.pseudos.eq;for(z in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})v.pseudos[z]=l(z);for(z in{submit:!0,
reset:!0})v.pseudos[z]=q(z);m.prototype=v.filters=v.pseudos;v.setFilters=new m;Ia=d.compile=function(a,b){var c,d=[],e=[],f=R[a+" "];if(!f){b||(b=n(a));for(c=b.length;c--;)f=G(b[c]),f[x]?d.push(f):e.push(f);f=R(a,rc(e,d))}return f};r.sortStable=x.split("").sort(N).join("")===x;r.detectDuplicates=I;ja();r.sortDetached=g(function(a){return a.compareDocumentPosition(y.createElement("div"))&1});g(function(a){a.innerHTML="<a href='#'></a>";return"#"===a.firstChild.getAttribute("href")})||h("type|href|height|width",
function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});r.attributes&&g(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")})||h("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});g(function(a){return null==a.getAttribute("disabled")})||h("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",function(a,
b,c){var d;if(!c)return(d=a.getAttributeNode(b))&&d.specified?d.value:!0===a[b]?b.toLowerCase():null});c.find=d;c.expr=d.selectors;c.expr[":"]=c.expr.pseudos;c.unique=d.uniqueSort;c.text=d.getText;c.isXMLDoc=d.isXML;c.contains=d.contains})(t);var Ta={};c.Callbacks=function(a){a="string"===typeof a?Ta[a]||Ub(a):c.extend({},a);var b,d,e,f,g,h,k=[],l=!a.once&&[],q=function(c){d=a.memory&&c;e=!0;g=h||0;h=0;f=k.length;for(b=!0;k&&g<f;g++)if(!1===k[g].apply(c[0],c[1])&&a.stopOnFalse){d=!1;break}b=!1;k&&
(l?l.length&&q(l.shift()):d?k=[]:u.disable())},u={add:function(){if(k){var e=k.length;(function L(b){c.each(b,function(b,d){var e=c.type(d);"function"===e?a.unique&&u.has(d)||k.push(d):d&&d.length&&"string"!==e&&L(d)})})(arguments);b?f=k.length:d&&(h=e,q(d))}return this},remove:function(){k&&c.each(arguments,function(a,d){for(var e;-1<(e=c.inArray(d,k,e));)k.splice(e,1),b&&(e<=f&&f--,e<=g&&g--)});return this},has:function(a){return a?-1<c.inArray(a,k):!(!k||!k.length)},empty:function(){k=[];f=0;return this},
disable:function(){k=l=d=n;return this},disabled:function(){return!k},lock:function(){l=n;d||u.disable();return this},locked:function(){return!l},fireWith:function(a,c){!k||e&&!l||(c=c||[],c=[a,c.slice?c.slice():c],b?l.push(c):q(c));return this},fire:function(){u.fireWith(this,arguments);return this},fired:function(){return!!e}};return u};c.extend({Deferred:function(a){var b=[["resolve","done",c.Callbacks("once memory"),"resolved"],["reject","fail",c.Callbacks("once memory"),"rejected"],["notify",
"progress",c.Callbacks("memory")]],d="pending",e={state:function(){return d},always:function(){f.done(arguments).fail(arguments);return this},then:function(){var a=arguments;return c.Deferred(function(d){c.each(b,function(b,l){var q=l[0],u=c.isFunction(a[b])&&a[b];f[l[1]](function(){var a=u&&u.apply(this,arguments);if(a&&c.isFunction(a.promise))a.promise().done(d.resolve).fail(d.reject).progress(d.notify);else d[q+"With"](this===e?d.promise():this,u?[a]:arguments)})});a=null}).promise()},promise:function(a){return null!=
a?c.extend(a,e):e}},f={};e.pipe=e.then;c.each(b,function(a,c){var k=c[2],l=c[3];e[c[1]]=k.add;l&&k.add(function(){d=l},b[a^1][2].disable,b[2][2].lock);f[c[0]]=function(){f[c[0]+"With"](this===f?e:this,arguments);return this};f[c[0]+"With"]=k.fireWith});e.promise(f);a&&a.call(f,f);return f},when:function(a){var b=0,d=D.call(arguments),e=d.length,f=1!==e||a&&c.isFunction(a.promise)?e:0,g=1===f?a:c.Deferred(),h=function(a,b,c){return function(d){b[a]=this;c[a]=1<arguments.length?D.call(arguments):d;
c===k?g.notifyWith(b,c):--f||g.resolveWith(b,c)}},k,l,q;if(1<e)for(k=Array(e),l=Array(e),q=Array(e);b<e;b++)d[b]&&c.isFunction(d[b].promise)?d[b].promise().done(h(b,q,d)).fail(g.reject).progress(h(b,l,k)):--f;f||g.resolveWith(q,d);return g.promise()}});c.support=function(a){var b,d,e,f,g,h,k=p.createElement("div");k.setAttribute("className","t");k.innerHTML="  <link/><table></table><a href='/a'>a</a><input type='checkbox'/>";b=k.getElementsByTagName("*")||[];d=k.getElementsByTagName("a")[0];if(!d||
!d.style||!b.length)return a;e=p.createElement("select");f=e.appendChild(p.createElement("option"));b=k.getElementsByTagName("input")[0];d.style.cssText="top:1px;float:left;opacity:.5";a.getSetAttribute="t"!==k.className;a.leadingWhitespace=3===k.firstChild.nodeType;a.tbody=!k.getElementsByTagName("tbody").length;a.htmlSerialize=!!k.getElementsByTagName("link").length;a.style=/top/.test(d.getAttribute("style"));a.hrefNormalized="/a"===d.getAttribute("href");a.opacity=/^0.5/.test(d.style.opacity);
a.cssFloat=!!d.style.cssFloat;a.checkOn=!!b.value;a.optSelected=f.selected;a.enctype=!!p.createElement("form").enctype;a.html5Clone="<:nav></:nav>"!==p.createElement("nav").cloneNode(!0).outerHTML;a.inlineBlockNeedsLayout=!1;a.shrinkWrapBlocks=!1;a.pixelPosition=!1;a.deleteExpando=!0;a.noCloneEvent=!0;a.reliableMarginRight=!0;a.boxSizingReliable=!0;b.checked=!0;a.noCloneChecked=b.cloneNode(!0).checked;e.disabled=!0;a.optDisabled=!f.disabled;try{delete k.test}catch(l){a.deleteExpando=!1}b=p.createElement("input");
b.setAttribute("value","");a.input=""===b.getAttribute("value");b.value="t";b.setAttribute("type","radio");a.radioValue="t"===b.value;b.setAttribute("checked","t");b.setAttribute("name","t");d=p.createDocumentFragment();d.appendChild(b);a.appendChecked=b.checked;a.checkClone=d.cloneNode(!0).cloneNode(!0).lastChild.checked;k.attachEvent&&(k.attachEvent("onclick",function(){a.noCloneEvent=!1}),k.cloneNode(!0).click());for(h in{submit:!0,change:!0,focusin:!0})k.setAttribute(d="on"+h,"t"),a[h+"Bubbles"]=
d in t||!1===k.attributes[d].expando;k.style.backgroundClip="content-box";k.cloneNode(!0).style.backgroundClip="";a.clearCloneStyle="content-box"===k.style.backgroundClip;for(h in c(a))break;a.ownLast="0"!==h;c(function(){var b,d,e=p.getElementsByTagName("body")[0];e&&(b=p.createElement("div"),b.style.cssText="border:0;width:0;height:0;position:absolute;top:0;left:-9999px;margin-top:1px",e.appendChild(b).appendChild(k),k.innerHTML="<table><tr><td></td><td>t</td></tr></table>",d=k.getElementsByTagName("td"),
d[0].style.cssText="padding:0;margin:0;border:0;display:none",g=0===d[0].offsetHeight,d[0].style.display="",d[1].style.display="none",a.reliableHiddenOffsets=g&&0===d[0].offsetHeight,k.innerHTML="",k.style.cssText="box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;padding:1px;border:1px;display:block;width:4px;margin-top:1%;position:absolute;top:1%;",c.swap(e,null!=e.style.zoom?{zoom:1}:{},function(){a.boxSizing=4===k.offsetWidth}),t.getComputedStyle&&(a.pixelPosition=
"1%"!==(t.getComputedStyle(k,null)||{}).top,a.boxSizingReliable="4px"===(t.getComputedStyle(k,null)||{width:"4px"}).width,d=k.appendChild(p.createElement("div")),d.style.cssText=k.style.cssText="padding:0;margin:0;border:0;display:block;box-sizing:content-box;-moz-box-sizing:content-box;-webkit-box-sizing:content-box;",d.style.marginRight=d.style.width="0",k.style.width="1px",a.reliableMarginRight=!parseFloat((t.getComputedStyle(d,null)||{}).marginRight)),typeof k.style.zoom!==A&&(k.innerHTML="",
k.style.cssText="padding:0;margin:0;border:0;display:block;box-sizing:content-box;-moz-box-sizing:content-box;-webkit-box-sizing:content-box;width:1px;padding:1px;display:inline;zoom:1",a.inlineBlockNeedsLayout=3===k.offsetWidth,k.style.display="block",k.innerHTML="<div></div>",k.firstChild.style.width="5px",a.shrinkWrapBlocks=3!==k.offsetWidth,a.inlineBlockNeedsLayout&&(e.style.zoom=1)),e.removeChild(b),b=k=d=d=null)});b=e=d=f=d=b=null;return a}({});var Wb=/(?:\{[\s\S]*\}|\[[\s\S]*\])$/,Vb=/([A-Z])/g;
c.extend({cache:{},noData:{applet:!0,embed:!0,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"},hasData:function(a){a=a.nodeType?c.cache[a[c.expando]]:a[c.expando];return!!a&&!ya(a)},data:function(a,b,c){return Ua(a,b,c)},removeData:function(a,b){return Va(a,b)},_data:function(a,b,c){return Ua(a,b,c,!0)},_removeData:function(a,b){return Va(a,b,!0)},acceptData:function(a){if(a.nodeType&&1!==a.nodeType&&9!==a.nodeType)return!1;var b=a.nodeName&&c.noData[a.nodeName.toLowerCase()];return!b||!0!==b&&
a.getAttribute("classid")===b}});c.fn.extend({data:function(a,b){var d,e,f=null,g=0,h=this[0];if(a===n){if(this.length&&(f=c.data(h),1===h.nodeType&&!c._data(h,"parsedAttrs"))){for(d=h.attributes;g<d.length;g++)e=d[g].name,0===e.indexOf("data-")&&(e=c.camelCase(e.slice(5)),Wa(h,e,f[e]));c._data(h,"parsedAttrs",!0)}return f}return"object"===typeof a?this.each(function(){c.data(this,a)}):1<arguments.length?this.each(function(){c.data(this,a,b)}):h?Wa(h,a,c.data(h,a)):null},removeData:function(a){return this.each(function(){c.removeData(this,
a)})}});c.extend({queue:function(a,b,d){var e;if(a)return b=(b||"fx")+"queue",e=c._data(a,b),d&&(!e||c.isArray(d)?e=c._data(a,b,c.makeArray(d)):e.push(d)),e||[]},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),e=d.length,f=d.shift(),g=c._queueHooks(a,b),h=function(){c.dequeue(a,b)};"inprogress"===f&&(f=d.shift(),e--);f&&("fx"===b&&d.unshift("inprogress"),delete g.stop,f.call(a,h,g));!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var d=b+"queueHooks";return c._data(a,d)||c._data(a,d,{empty:c.Callbacks("once memory").add(function(){c._removeData(a,
b+"queue");c._removeData(a,d)})})}});c.fn.extend({queue:function(a,b){var d=2;"string"!==typeof a&&(b=a,a="fx",d--);return arguments.length<d?c.queue(this[0],a):b===n?this:this.each(function(){var d=c.queue(this,a,b);c._queueHooks(this,a);"fx"===a&&"inprogress"!==d[0]&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;return this.queue(b||"fx",function(b,c){var f=setTimeout(b,a);c.stop=function(){clearTimeout(f)}})},
clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var d,e=1,f=c.Deferred(),g=this,h=this.length,k=function(){--e||f.resolveWith(g,[g])};"string"!==typeof a&&(b=a,a=n);for(a=a||"fx";h--;)(d=c._data(g[h],a+"queueHooks"))&&d.empty&&(e++,d.empty.add(k));k();return f.promise(b)}});var S,Bb,Ja=/[\t\r\n\f]/g,sc=/\r/g,tc=/^(?:input|select|textarea|button|object)$/i,uc=/^(?:a|area)$/i,Ka=/^(?:checked|selected)$/i,Z=c.support.getSetAttribute,sa=c.support.input;c.fn.extend({attr:function(a,
b){return c.access(this,c.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){c.removeAttr(this,a)})},prop:function(a,b){return c.access(this,c.prop,a,b,1<arguments.length)},removeProp:function(a){a=c.propFix[a]||a;return this.each(function(){try{this[a]=n,delete this[a]}catch(b){}})},addClass:function(a){var b,d,e,f,g,h=0,k=this.length;b="string"===typeof a&&a;if(c.isFunction(a))return this.each(function(b){c(this).addClass(a.call(this,b,this.className))});if(b)for(b=
(a||"").match(F)||[];h<k;h++)if(d=this[h],e=1===d.nodeType&&(d.className?(" "+d.className+" ").replace(Ja," "):" ")){for(g=0;f=b[g++];)0>e.indexOf(" "+f+" ")&&(e+=f+" ");d.className=c.trim(e)}return this},removeClass:function(a){var b,d,e,f,g,h=0,k=this.length;b=0===arguments.length||"string"===typeof a&&a;if(c.isFunction(a))return this.each(function(b){c(this).removeClass(a.call(this,b,this.className))});if(b)for(b=(a||"").match(F)||[];h<k;h++)if(d=this[h],e=1===d.nodeType&&(d.className?(" "+d.className+
" ").replace(Ja," "):"")){for(g=0;f=b[g++];)for(;0<=e.indexOf(" "+f+" ");)e=e.replace(" "+f+" "," ");d.className=a?c.trim(e):""}return this},toggleClass:function(a,b){var d=typeof a;return"boolean"===typeof b&&"string"===d?b?this.addClass(a):this.removeClass(a):c.isFunction(a)?this.each(function(d){c(this).toggleClass(a.call(this,d,this.className,b),b)}):this.each(function(){if("string"===d)for(var b,f=0,g=c(this),h=a.match(F)||[];b=h[f++];)g.hasClass(b)?g.removeClass(b):g.addClass(b);else if(d===
A||"boolean"===d)this.className&&c._data(this,"__className__",this.className),this.className=this.className||!1===a?"":c._data(this,"__className__")||""})},hasClass:function(a){a=" "+a+" ";for(var b=0,c=this.length;b<c;b++)if(1===this[b].nodeType&&0<=(" "+this[b].className+" ").replace(Ja," ").indexOf(a))return!0;return!1},val:function(a){var b,d,e,f=this[0];if(arguments.length)return e=c.isFunction(a),this.each(function(b){1===this.nodeType&&(b=e?a.call(this,b,c(this).val()):a,null==b?b="":"number"===
typeof b?b+="":c.isArray(b)&&(b=c.map(b,function(a){return null==a?"":a+""})),d=c.valHooks[this.type]||c.valHooks[this.nodeName.toLowerCase()],d&&"set"in d&&d.set(this,b,"value")!==n||(this.value=b))});if(f){if((d=c.valHooks[f.type]||c.valHooks[f.nodeName.toLowerCase()])&&"get"in d&&(b=d.get(f,"value"))!==n)return b;b=f.value;return"string"===typeof b?b.replace(sc,""):null==b?"":b}}});c.extend({valHooks:{option:{get:function(a){var b=c.find.attr(a,"value");return null!=b?b:a.text}},select:{get:function(a){for(var b,
d=a.options,e=a.selectedIndex,f=(a="select-one"===a.type||0>e)?null:[],g=a?e+1:d.length,h=0>e?g:a?e:0;h<g;h++)if(b=d[h],!(!b.selected&&h!==e||(c.support.optDisabled?b.disabled:null!==b.getAttribute("disabled"))||b.parentNode.disabled&&c.nodeName(b.parentNode,"optgroup"))){b=c(b).val();if(a)return b;f.push(b)}return f},set:function(a,b){for(var d,e,f=a.options,g=c.makeArray(b),h=f.length;h--;)if(e=f[h],e.selected=0<=c.inArray(c(e).val(),g))d=!0;d||(a.selectedIndex=-1);return g}}},attr:function(a,b,
d){var e,f,g=a.nodeType;if(a&&3!==g&&8!==g&&2!==g){if(typeof a.getAttribute===A)return c.prop(a,b,d);1===g&&c.isXMLDoc(a)||(b=b.toLowerCase(),e=c.attrHooks[b]||(c.expr.match.bool.test(b)?Bb:S));if(d!==n)if(null===d)c.removeAttr(a,b);else{if(e&&"set"in e&&(f=e.set(a,d,b))!==n)return f;a.setAttribute(b,d+"");return d}else{if(e&&"get"in e&&null!==(f=e.get(a,b)))return f;f=c.find.attr(a,b);return null==f?n:f}}},removeAttr:function(a,b){var d,e,f=0,g=b&&b.match(F);if(g&&1===a.nodeType)for(;d=g[f++];)e=
c.propFix[d]||d,c.expr.match.bool.test(d)?sa&&Z||!Ka.test(d)?a[e]=!1:a[c.camelCase("default-"+d)]=a[e]=!1:c.attr(a,d,""),a.removeAttribute(Z?d:e)},attrHooks:{type:{set:function(a,b){if(!c.support.radioValue&&"radio"===b&&c.nodeName(a,"input")){var d=a.value;a.setAttribute("type",b);d&&(a.value=d);return b}}}},propFix:{"for":"htmlFor","class":"className"},prop:function(a,b,d){var e,f,g;g=a.nodeType;if(a&&3!==g&&8!==g&&2!==g)return 1===g&&c.isXMLDoc(a)||(b=c.propFix[b]||b,f=c.propHooks[b]),d!==n?f&&
"set"in f&&(e=f.set(a,d,b))!==n?e:a[b]=d:f&&"get"in f&&null!==(e=f.get(a,b))?e:a[b]},propHooks:{tabIndex:{get:function(a){var b=c.find.attr(a,"tabindex");return b?parseInt(b,10):tc.test(a.nodeName)||uc.test(a.nodeName)&&a.href?0:-1}}}});Bb={set:function(a,b,d){!1===b?c.removeAttr(a,d):sa&&Z||!Ka.test(d)?a.setAttribute(!Z&&c.propFix[d]||d,d):a[c.camelCase("default-"+d)]=a[d]=!0;return d}};c.each(c.expr.match.bool.source.match(/\w+/g),function(a,b){var d=c.expr.attrHandle[b]||c.find.attr;c.expr.attrHandle[b]=
sa&&Z||!Ka.test(b)?function(a,b,g){var h=c.expr.attrHandle[b];a=g?n:(c.expr.attrHandle[b]=n)!=d(a,b,g)?b.toLowerCase():null;c.expr.attrHandle[b]=h;return a}:function(a,b,d){return d?n:a[c.camelCase("default-"+b)]?b.toLowerCase():null}});sa&&Z||(c.attrHooks.value={set:function(a,b,d){if(c.nodeName(a,"input"))a.defaultValue=b;else return S&&S.set(a,b,d)}});Z||(S={set:function(a,b,c){var e=a.getAttributeNode(c);e||a.setAttributeNode(e=a.ownerDocument.createAttribute(c));e.value=b+="";return"value"===
c||b===a.getAttribute(c)?b:n}},c.expr.attrHandle.id=c.expr.attrHandle.name=c.expr.attrHandle.coords=function(a,b,c){var e;return c?n:(e=a.getAttributeNode(b))&&""!==e.value?e.value:null},c.valHooks.button={get:function(a,b){var c=a.getAttributeNode(b);return c&&c.specified?c.value:n},set:S.set},c.attrHooks.contenteditable={set:function(a,b,c){S.set(a,""===b?!1:b,c)}},c.each(["width","height"],function(a,b){c.attrHooks[b]={set:function(a,c){if(""===c)return a.setAttribute(b,"auto"),c}}}));c.support.hrefNormalized||
c.each(["href","src"],function(a,b){c.propHooks[b]={get:function(a){return a.getAttribute(b,4)}}});c.support.style||(c.attrHooks.style={get:function(a){return a.style.cssText||n},set:function(a,b){return a.style.cssText=b+""}});c.support.optSelected||(c.propHooks.selected={get:function(a){if(a=a.parentNode)a.selectedIndex,a.parentNode&&a.parentNode.selectedIndex;return null}});c.each("tabIndex readOnly maxLength cellSpacing cellPadding rowSpan colSpan useMap frameBorder contentEditable".split(" "),
function(){c.propFix[this.toLowerCase()]=this});c.support.enctype||(c.propFix.enctype="encoding");c.each(["radio","checkbox"],function(){c.valHooks[this]={set:function(a,b){if(c.isArray(b))return a.checked=0<=c.inArray(c(a).val(),b)}};c.support.checkOn||(c.valHooks[this].get=function(a){return null===a.getAttribute("value")?"on":a.value})});var La=/^(?:input|select|textarea)$/i,vc=/^key/,wc=/^(?:mouse|contextmenu)|click/,Cb=/^(?:focusinfocus|focusoutblur)$/,Db=/^([^.]*)(?:\.(.+)|)$/;c.event={global:{},
add:function(a,b,d,e,f){var g,h,k,l,q,u,m,w,p;if(k=c._data(a)){d.handler&&(l=d,d=l.handler,f=l.selector);d.guid||(d.guid=c.guid++);(h=k.events)||(h=k.events={});(q=k.handle)||(q=k.handle=function(a){return typeof c===A||a&&c.event.triggered===a.type?n:c.event.dispatch.apply(q.elem,arguments)},q.elem=a);b=(b||"").match(F)||[""];for(k=b.length;k--;)g=Db.exec(b[k])||[],w=u=g[1],p=(g[2]||"").split(".").sort(),w&&(g=c.event.special[w]||{},w=(f?g.delegateType:g.bindType)||w,g=c.event.special[w]||{},u=c.extend({type:w,
origType:u,data:e,handler:d,guid:d.guid,selector:f,needsContext:f&&c.expr.match.needsContext.test(f),namespace:p.join(".")},l),(m=h[w])||(m=h[w]=[],m.delegateCount=0,g.setup&&!1!==g.setup.call(a,e,p,q)||(a.addEventListener?a.addEventListener(w,q,!1):a.attachEvent&&a.attachEvent("on"+w,q))),g.add&&(g.add.call(a,u),u.handler.guid||(u.handler.guid=d.guid)),f?m.splice(m.delegateCount++,0,u):m.push(u),c.event.global[w]=!0);a=null}},remove:function(a,b,d,e,f){var g,h,k,l,q,n,m,w,p,t,C,z=c.hasData(a)&&c._data(a);
if(z&&(n=z.events)){b=(b||"").match(F)||[""];for(q=b.length;q--;)if(k=Db.exec(b[q])||[],p=C=k[1],t=(k[2]||"").split(".").sort(),p){m=c.event.special[p]||{};p=(e?m.delegateType:m.bindType)||p;w=n[p]||[];k=k[2]&&new RegExp("(^|\\.)"+t.join("\\.(?:.*\\.|)")+"(\\.|$)");for(l=g=w.length;g--;)h=w[g],!f&&C!==h.origType||d&&d.guid!==h.guid||k&&!k.test(h.namespace)||e&&e!==h.selector&&("**"!==e||!h.selector)||(w.splice(g,1),h.selector&&w.delegateCount--,m.remove&&m.remove.call(a,h));l&&!w.length&&(m.teardown&&
!1!==m.teardown.call(a,t,z.handle)||c.removeEvent(a,p,z.handle),delete n[p])}else for(p in n)c.event.remove(a,p+b[q],d,e,!0);c.isEmptyObject(n)&&(delete z.handle,c._removeData(a,"events"))}},trigger:function(a,b,d,e){var f,g,h,k,l,q,u=[d||p],m=X.call(a,"type")?a.type:a;l=X.call(a,"namespace")?a.namespace.split("."):[];h=f=d=d||p;if(3!==d.nodeType&&8!==d.nodeType&&!Cb.test(m+c.event.triggered)&&(0<=m.indexOf(".")&&(l=m.split("."),m=l.shift(),l.sort()),g=0>m.indexOf(":")&&"on"+m,a=a[c.expando]?a:new c.Event(m,
"object"===typeof a&&a),a.isTrigger=e?2:3,a.namespace=l.join("."),a.namespace_re=a.namespace?new RegExp("(^|\\.)"+l.join("\\.(?:.*\\.|)")+"(\\.|$)"):null,a.result=n,a.target||(a.target=d),b=null==b?[a]:c.makeArray(b,[a]),l=c.event.special[m]||{},e||!l.trigger||!1!==l.trigger.apply(d,b))){if(!e&&!l.noBubble&&!c.isWindow(d)){k=l.delegateType||m;for(Cb.test(k+m)||(h=h.parentNode);h;h=h.parentNode)u.push(h),f=h;f===(d.ownerDocument||p)&&u.push(f.defaultView||f.parentWindow||t)}for(q=0;(h=u[q++])&&!a.isPropagationStopped();)a.type=
1<q?k:l.bindType||m,(f=(c._data(h,"events")||{})[a.type]&&c._data(h,"handle"))&&f.apply(h,b),(f=g&&h[g])&&c.acceptData(h)&&f.apply&&!1===f.apply(h,b)&&a.preventDefault();a.type=m;if(!(e||a.isDefaultPrevented()||l._default&&!1!==l._default.apply(u.pop(),b))&&c.acceptData(d)&&g&&d[m]&&!c.isWindow(d)){(f=d[g])&&(d[g]=null);c.event.triggered=m;try{d[m]()}catch(w){}c.event.triggered=n;f&&(d[g]=f)}return a.result}},dispatch:function(a){a=c.event.fix(a);var b,d,e,f,g=[],h=D.call(arguments);b=(c._data(this,
"events")||{})[a.type]||[];var k=c.event.special[a.type]||{};h[0]=a;a.delegateTarget=this;if(!k.preDispatch||!1!==k.preDispatch.call(this,a)){g=c.event.handlers.call(this,a,b);for(b=0;(e=g[b++])&&!a.isPropagationStopped();)for(a.currentTarget=e.elem,f=0;(d=e.handlers[f++])&&!a.isImmediatePropagationStopped();)if(!a.namespace_re||a.namespace_re.test(d.namespace))a.handleObj=d,a.data=d.data,d=((c.event.special[d.origType]||{}).handle||d.handler).apply(e.elem,h),d!==n&&!1===(a.result=d)&&(a.preventDefault(),
a.stopPropagation());k.postDispatch&&k.postDispatch.call(this,a);return a.result}},handlers:function(a,b){var d,e,f,g,h=[],k=b.delegateCount,l=a.target;if(k&&l.nodeType&&(!a.button||"click"!==a.type))for(;l!=this;l=l.parentNode||this)if(1===l.nodeType&&(!0!==l.disabled||"click"!==a.type)){f=[];for(g=0;g<k;g++)e=b[g],d=e.selector+" ",f[d]===n&&(f[d]=e.needsContext?0<=c(d,this).index(l):c.find(d,this,null,[l]).length),f[d]&&f.push(e);f.length&&h.push({elem:l,handlers:f})}k<b.length&&h.push({elem:this,
handlers:b.slice(k)});return h},fix:function(a){if(a[c.expando])return a;var b,d,e;b=a.type;var f=a,g=this.fixHooks[b];g||(this.fixHooks[b]=g=wc.test(b)?this.mouseHooks:vc.test(b)?this.keyHooks:{});e=g.props?this.props.concat(g.props):this.props;a=new c.Event(f);for(b=e.length;b--;)d=e[b],a[d]=f[d];a.target||(a.target=f.srcElement||p);3===a.target.nodeType&&(a.target=a.target.parentNode);a.metaKey=!!a.metaKey;return g.filter?g.filter(a,f):a},props:"altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),
fixHooks:{},keyHooks:{props:["char","charCode","key","keyCode"],filter:function(a,b){null==a.which&&(a.which=null!=b.charCode?b.charCode:b.keyCode);return a}},mouseHooks:{props:"button buttons clientX clientY fromElement offsetX offsetY pageX pageY screenX screenY toElement".split(" "),filter:function(a,b){var c,e,f=b.button,g=b.fromElement;null==a.pageX&&null!=b.clientX&&(c=a.target.ownerDocument||p,e=c.documentElement,c=c.body,a.pageX=b.clientX+(e&&e.scrollLeft||c&&c.scrollLeft||0)-(e&&e.clientLeft||
c&&c.clientLeft||0),a.pageY=b.clientY+(e&&e.scrollTop||c&&c.scrollTop||0)-(e&&e.clientTop||c&&c.clientTop||0));!a.relatedTarget&&g&&(a.relatedTarget=g===a.target?b.toElement:g);a.which||f===n||(a.which=f&1?1:f&2?3:f&4?2:0);return a}},special:{load:{noBubble:!0},focus:{trigger:function(){if(this!==Xa()&&this.focus)try{return this.focus(),!1}catch(a){}},delegateType:"focusin"},blur:{trigger:function(){if(this===Xa()&&this.blur)return this.blur(),!1},delegateType:"focusout"},click:{trigger:function(){if(c.nodeName(this,
"input")&&"checkbox"===this.type&&this.click)return this.click(),!1},_default:function(a){return c.nodeName(a.target,"a")}},beforeunload:{postDispatch:function(a){a.result!==n&&(a.originalEvent.returnValue=a.result)}}},simulate:function(a,b,d,e){a=c.extend(new c.Event,d,{type:a,isSimulated:!0,originalEvent:{}});e?c.event.trigger(a,null,b):c.event.dispatch.call(b,a);a.isDefaultPrevented()&&d.preventDefault()}};c.removeEvent=p.removeEventListener?function(a,b,c){a.removeEventListener&&a.removeEventListener(b,
c,!1)}:function(a,b,c){b="on"+b;a.detachEvent&&(typeof a[b]===A&&(a[b]=null),a.detachEvent(b,c))};c.Event=function(a,b){if(!(this instanceof c.Event))return new c.Event(a,b);a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||!1===a.returnValue||a.getPreventDefault&&a.getPreventDefault()?na:T):this.type=a;b&&c.extend(this,b);this.timeStamp=a&&a.timeStamp||c.now();this[c.expando]=!0};c.Event.prototype={isDefaultPrevented:T,isPropagationStopped:T,isImmediatePropagationStopped:T,
preventDefault:function(){var a=this.originalEvent;this.isDefaultPrevented=na;a&&(a.preventDefault?a.preventDefault():a.returnValue=!1)},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=na;a&&(a.stopPropagation&&a.stopPropagation(),a.cancelBubble=!0)},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=na;this.stopPropagation()}};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={delegateType:b,bindType:b,handle:function(a){var e,
f=a.relatedTarget,g=a.handleObj;if(!f||f!==this&&!c.contains(this,f))a.type=g.origType,e=g.handler.apply(this,arguments),a.type=b;return e}}});c.support.submitBubbles||(c.event.special.submit={setup:function(){if(c.nodeName(this,"form"))return!1;c.event.add(this,"click._submit keypress._submit",function(a){a=a.target;(a=c.nodeName(a,"input")||c.nodeName(a,"button")?a.form:n)&&!c._data(a,"submitBubbles")&&(c.event.add(a,"submit._submit",function(a){a._submit_bubble=!0}),c._data(a,"submitBubbles",!0))})},
postDispatch:function(a){a._submit_bubble&&(delete a._submit_bubble,this.parentNode&&!a.isTrigger&&c.event.simulate("submit",this.parentNode,a,!0))},teardown:function(){if(c.nodeName(this,"form"))return!1;c.event.remove(this,"._submit")}});c.support.changeBubbles||(c.event.special.change={setup:function(){if(La.test(this.nodeName)){if("checkbox"===this.type||"radio"===this.type)c.event.add(this,"propertychange._change",function(a){"checked"===a.originalEvent.propertyName&&(this._just_changed=!0)}),
c.event.add(this,"click._change",function(a){this._just_changed&&!a.isTrigger&&(this._just_changed=!1);c.event.simulate("change",this,a,!0)});return!1}c.event.add(this,"beforeactivate._change",function(a){a=a.target;La.test(a.nodeName)&&!c._data(a,"changeBubbles")&&(c.event.add(a,"change._change",function(a){!this.parentNode||a.isSimulated||a.isTrigger||c.event.simulate("change",this.parentNode,a,!0)}),c._data(a,"changeBubbles",!0))})},handle:function(a){var b=a.target;if(this!==b||a.isSimulated||
a.isTrigger||"radio"!==b.type&&"checkbox"!==b.type)return a.handleObj.handler.apply(this,arguments)},teardown:function(){c.event.remove(this,"._change");return!La.test(this.nodeName)}});c.support.focusinBubbles||c.each({focus:"focusin",blur:"focusout"},function(a,b){var d=0,e=function(a){c.event.simulate(b,a.target,c.event.fix(a),!0)};c.event.special[b]={setup:function(){0===d++&&p.addEventListener(a,e,!0)},teardown:function(){0===--d&&p.removeEventListener(a,e,!0)}}});c.fn.extend({on:function(a,
b,d,e,f){var g,h;if("object"===typeof a){"string"!==typeof b&&(d=d||b,b=n);for(g in a)this.on(g,b,d,a[g],f);return this}null==d&&null==e?(e=b,d=b=n):null==e&&("string"===typeof b?(e=d,d=n):(e=d,d=b,b=n));if(!1===e)e=T;else if(!e)return this;1===f&&(h=e,e=function(a){c().off(a);return h.apply(this,arguments)},e.guid=h.guid||(h.guid=c.guid++));return this.each(function(){c.event.add(this,a,e,d,b)})},one:function(a,b,c,e){return this.on(a,b,c,e,1)},off:function(a,b,d){var e;if(a&&a.preventDefault&&a.handleObj)return e=
a.handleObj,c(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler),this;if("object"===typeof a){for(e in a)this.off(e,b,a[e]);return this}if(!1===b||"function"===typeof b)d=b,b=n;!1===d&&(d=T);return this.each(function(){c.event.remove(this,a,d,b)})},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){var d=this[0];if(d)return c.event.trigger(a,b,d,!0)}});var Xb=/^.[^:#\[\.,]*$/,xc=/^(?:parents|prev(?:Until|All))/,
Eb=c.expr.match.needsContext,yc={children:!0,contents:!0,next:!0,prev:!0};c.fn.extend({find:function(a){var b,d=[],e=this,f=e.length;if("string"!==typeof a)return this.pushStack(c(a).filter(function(){for(b=0;b<f;b++)if(c.contains(e[b],this))return!0}));for(b=0;b<f;b++)c.find(a,e[b],d);d=this.pushStack(1<f?c.unique(d):d);d.selector=this.selector?this.selector+" "+a:a;return d},has:function(a){var b,d=c(a,this),e=d.length;return this.filter(function(){for(b=0;b<e;b++)if(c.contains(this,d[b]))return!0})},
not:function(a){return this.pushStack(za(this,a||[],!0))},filter:function(a){return this.pushStack(za(this,a||[],!1))},is:function(a){return!!za(this,"string"===typeof a&&Eb.test(a)?c(a):a||[],!1).length},closest:function(a,b){for(var d,e=0,f=this.length,g=[],h=Eb.test(a)||"string"!==typeof a?c(a,b||this.context):0;e<f;e++)for(d=this[e];d&&d!==b;d=d.parentNode)if(11>d.nodeType&&(h?-1<h.index(d):1===d.nodeType&&c.find.matchesSelector(d,a))){g.push(d);break}return this.pushStack(1<g.length?c.unique(g):
g)},index:function(a){return a?"string"===typeof a?c.inArray(this[0],c(a)):c.inArray(a.jquery?a[0]:a,this):this[0]&&this[0].parentNode?this.first().prevAll().length:-1},add:function(a,b){var d="string"===typeof a?c(a,b):c.makeArray(a&&a.nodeType?[a]:a),d=c.merge(this.get(),d);return this.pushStack(c.unique(d))},addBack:function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))}});c.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return c.dir(a,
"parentNode")},parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return Ya(a,"nextSibling")},prev:function(a){return Ya(a,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling((a.parentNode||{}).firstChild,a)},children:function(a){return c.sibling(a.firstChild)},
contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:c.merge([],a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var f=c.map(this,b,d);"Until"!==a.slice(-5)&&(e=d);e&&"string"===typeof e&&(f=c.filter(e,f));1<this.length&&(yc[a]||(f=c.unique(f)),xc.test(a)&&(f=f.reverse()));return this.pushStack(f)}});c.extend({filter:function(a,b,d){var e=b[0];d&&(a=":not("+a+")");return 1===b.length&&1===e.nodeType?c.find.matchesSelector(e,a)?[e]:[]:c.find.matches(a,c.grep(b,
function(a){return 1===a.nodeType}))},dir:function(a,b,d){var e=[];for(a=a[b];a&&9!==a.nodeType&&(d===n||1!==a.nodeType||!c(a).is(d));)1===a.nodeType&&e.push(a),a=a[b];return e},sibling:function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c}});var $a="abbr|article|aside|audio|bdi|canvas|data|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",zc=/ jQuery\d+="(?:null|\d+)"/g,Fb=new RegExp("<(?:"+$a+")[\\s/>]",
"i"),Ma=/^\s+/,Gb=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi,Hb=/<([\w:]+)/,Ib=/<tbody/i,Ac=/<|&#?\w+;/,Bc=/<(?:script|style|link)/i,Ba=/^(?:checkbox|radio)$/i,Cc=/checked\s*(?:[^=]|=\s*.checked.)/i,Jb=/^$|\/(?:java|ecma)script/i,Yb=/^true\/(.*)/,Dc=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g,z={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],area:[1,"<map>","</map>"],param:[1,"<object>","</object>"],thead:[1,"<table>","</table>"],
tr:[2,"<table><tbody>","</tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],_default:c.support.htmlSerialize?[0,"",""]:[1,"X<div>","</div>"]},Na=Za(p).appendChild(p.createElement("div"));z.optgroup=z.option;z.tbody=z.tfoot=z.colgroup=z.caption=z.thead;z.th=z.td;c.fn.extend({text:function(a){return c.access(this,function(a){return a===n?c.text(this):this.empty().append((this[0]&&this[0].ownerDocument||p).createTextNode(a))},
null,a,arguments.length)},append:function(){return this.domManip(arguments,function(a){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||ab(this,a).appendChild(a)})},prepend:function(){return this.domManip(arguments,function(a){if(1===this.nodeType||11===this.nodeType||9===this.nodeType){var b=ab(this,a);b.insertBefore(a,b.firstChild)}})},before:function(){return this.domManip(arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return this.domManip(arguments,
function(a){this.parentNode&&this.parentNode.insertBefore(a,this.nextSibling)})},remove:function(a,b){for(var d,e=a?c.filter(a,this):this,f=0;null!=(d=e[f]);f++)b||1!==d.nodeType||c.cleanData(C(d)),d.parentNode&&(b&&c.contains(d.ownerDocument,d)&&Aa(C(d,"script")),d.parentNode.removeChild(d));return this},empty:function(){for(var a,b=0;null!=(a=this[b]);b++){for(1===a.nodeType&&c.cleanData(C(a,!1));a.firstChild;)a.removeChild(a.firstChild);a.options&&c.nodeName(a,"select")&&(a.options.length=0)}return this},
clone:function(a,b){a=null==a?!1:a;b=null==b?a:b;return this.map(function(){return c.clone(this,a,b)})},html:function(a){return c.access(this,function(a){var d=this[0]||{},e=0,f=this.length;if(a===n)return 1===d.nodeType?d.innerHTML.replace(zc,""):n;if(!("string"!==typeof a||Bc.test(a)||!c.support.htmlSerialize&&Fb.test(a)||!c.support.leadingWhitespace&&Ma.test(a)||z[(Hb.exec(a)||["",""])[1].toLowerCase()])){a=a.replace(Gb,"<$1></$2>");try{for(;e<f;e++)d=this[e]||{},1===d.nodeType&&(c.cleanData(C(d,
!1)),d.innerHTML=a);d=0}catch(g){}}d&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(){var a=c.map(this,function(a){return[a.nextSibling,a.parentNode]}),b=0;this.domManip(arguments,function(d){var e=a[b++],f=a[b++];f&&(e&&e.parentNode!==f&&(e=this.nextSibling),c(this).remove(),f.insertBefore(d,e))},!0);return b?this:this.remove()},detach:function(a){return this.remove(a,!0)},domManip:function(a,b,d){a=wb.apply([],a);var e,f,g,h,k=0,l=this.length,q=this,n=l-1,m=a[0],p=c.isFunction(m);
if(p||!(1>=l||"string"!==typeof m||c.support.checkClone)&&Cc.test(m))return this.each(function(c){var e=q.eq(c);p&&(a[0]=m.call(this,c,e.html()));e.domManip(a,b,d)});if(l&&(h=c.buildFragment(a,this[0].ownerDocument,!1,!d&&this),e=h.firstChild,1===h.childNodes.length&&(h=e),e)){g=c.map(C(h,"script"),bb);for(f=g.length;k<l;k++)e=h,k!==n&&(e=c.clone(e,!0,!0),f&&c.merge(g,C(e,"script"))),b.call(this[k],e,k);if(f)for(h=g[g.length-1].ownerDocument,c.map(g,cb),k=0;k<f;k++)e=g[k],Jb.test(e.type||"")&&!c._data(e,
"globalEval")&&c.contains(h,e)&&(e.src?c._evalUrl(e.src):c.globalEval((e.text||e.textContent||e.innerHTML||"").replace(Dc,"")));h=e=null}return this}});c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(a){for(var e=0,f=[],g=c(a),h=g.length-1;e<=h;e++)a=e===h?this:this.clone(!0),c(g[e])[b](a),Fa.apply(f,a.get());return this.pushStack(f)}});c.extend({clone:function(a,b,d){var e,f,g,h,k,l=c.contains(a.ownerDocument,
a);c.support.html5Clone||c.isXMLDoc(a)||!Fb.test("<"+a.nodeName+">")?g=a.cloneNode(!0):(Na.innerHTML=a.outerHTML,Na.removeChild(g=Na.firstChild));if(!(c.support.noCloneEvent&&c.support.noCloneChecked||1!==a.nodeType&&11!==a.nodeType||c.isXMLDoc(a)))for(e=C(g),k=C(a),h=0;null!=(f=k[h]);++h)if(e[h]){var q=e[h],n=void 0,m=void 0,p=void 0;if(1===q.nodeType){n=q.nodeName.toLowerCase();if(!c.support.noCloneEvent&&q[c.expando]){p=c._data(q);for(m in p.events)c.removeEvent(q,m,p.handle);q.removeAttribute(c.expando)}if("script"===
n&&q.text!==f.text)bb(q).text=f.text,cb(q);else if("object"===n)q.parentNode&&(q.outerHTML=f.outerHTML),c.support.html5Clone&&f.innerHTML&&!c.trim(q.innerHTML)&&(q.innerHTML=f.innerHTML);else if("input"===n&&Ba.test(f.type))q.defaultChecked=q.checked=f.checked,q.value!==f.value&&(q.value=f.value);else if("option"===n)q.defaultSelected=q.selected=f.defaultSelected;else if("input"===n||"textarea"===n)q.defaultValue=f.defaultValue}}if(b)if(d)for(k=k||C(a),e=e||C(g),h=0;null!=(f=k[h]);h++)db(f,e[h]);
else db(a,g);e=C(g,"script");0<e.length&&Aa(e,!l&&C(a,"script"));return g},buildFragment:function(a,b,d,e){for(var f,g,h,k,l,q,n=a.length,m=Za(b),p=[],t=0;t<n;t++)if((g=a[t])||0===g)if("object"===c.type(g))c.merge(p,g.nodeType?[g]:g);else if(Ac.test(g)){h=h||m.appendChild(b.createElement("div"));k=(Hb.exec(g)||["",""])[1].toLowerCase();q=z[k]||z._default;h.innerHTML=q[1]+g.replace(Gb,"<$1></$2>")+q[2];for(f=q[0];f--;)h=h.lastChild;!c.support.leadingWhitespace&&Ma.test(g)&&p.push(b.createTextNode(Ma.exec(g)[0]));
if(!c.support.tbody)for(f=(g="table"!==k||Ib.test(g)?"<table>"!==q[1]||Ib.test(g)?0:h:h.firstChild)&&g.childNodes.length;f--;)c.nodeName(l=g.childNodes[f],"tbody")&&!l.childNodes.length&&g.removeChild(l);c.merge(p,h.childNodes);for(h.textContent="";h.firstChild;)h.removeChild(h.firstChild);h=m.lastChild}else p.push(b.createTextNode(g));h&&m.removeChild(h);c.support.appendChecked||c.grep(C(p,"input"),Zb);for(t=0;g=p[t++];)if(!e||-1===c.inArray(g,e))if(a=c.contains(g.ownerDocument,g),h=C(m.appendChild(g),
"script"),a&&Aa(h),d)for(f=0;g=h[f++];)Jb.test(g.type||"")&&d.push(g);return m},cleanData:function(a,b){for(var d,e,f,g,h=0,k=c.expando,l=c.cache,n=c.support.deleteExpando,p=c.event.special;null!=(d=a[h]);h++)if(b||c.acceptData(d))if(g=(f=d[k])&&l[f]){if(g.events)for(e in g.events)p[e]?c.event.remove(d,e):c.removeEvent(d,e,g.handle);l[f]&&(delete l[f],n?delete d[k]:typeof d.removeAttribute!==A?d.removeAttribute(k):d[k]=null,ba.push(f))}},_evalUrl:function(a){return c.ajax({url:a,type:"GET",dataType:"script",
async:!1,global:!1,"throws":!0})}});c.fn.extend({wrapAll:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapAll(a.call(this,b))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(!0);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var a=this;a.firstChild&&1===a.firstChild.nodeType;)a=a.firstChild;return a}).append(this)}return this},wrapInner:function(a){return c.isFunction(a)?this.each(function(b){c(this).wrapInner(a.call(this,b))}):this.each(function(){var b=
c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){var b=c.isFunction(a);return this.each(function(d){c(this).wrapAll(b?a.call(this,d):a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()}});var ia,I,N,Oa=/alpha\([^)]*\)/i,Ec=/opacity\s*=\s*([^)]*)/,Fc=/^(top|right|bottom|left)$/,Gc=/^(none|table(?!-c[ea]).+)/,Kb=/^margin/,$b=new RegExp("^("+ra+")(.*)$","i"),oa=new RegExp("^("+ra+")(?!px)[a-z%]+$",
"i"),Hc=new RegExp("^([+-])=("+ra+")","i"),lb={BODY:"block"},Ic={position:"absolute",visibility:"hidden",display:"block"},Lb={letterSpacing:0,fontWeight:400},R=["Top","Right","Bottom","Left"],fb=["Webkit","O","Moz","ms"];c.fn.extend({css:function(a,b){return c.access(this,function(a,b,f){var g,h={},k=0;if(c.isArray(b)){g=I(a);for(f=b.length;k<f;k++)h[b[k]]=c.css(a,b[k],!1,g);return h}return f!==n?c.style(a,b,f):c.css(a,b)},a,b,1<arguments.length)},show:function(){return gb(this,!0)},hide:function(){return gb(this)},
toggle:function(a){return"boolean"===typeof a?a?this.show():this.hide():this.each(function(){ha(this)?c(this).show():c(this).hide()})}});c.extend({cssHooks:{opacity:{get:function(a,b){if(b){var c=N(a,"opacity");return""===c?"1":c}}}},cssNumber:{columnCount:!0,fillOpacity:!0,fontWeight:!0,lineHeight:!0,opacity:!0,order:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":c.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,b,d,e){if(a&&3!==a.nodeType&&8!==a.nodeType&&a.style){var f,
g,h,k=c.camelCase(b),l=a.style;b=c.cssProps[k]||(c.cssProps[k]=eb(l,k));h=c.cssHooks[b]||c.cssHooks[k];if(d!==n){if(g=typeof d,"string"===g&&(f=Hc.exec(d))&&(d=(f[1]+1)*f[2]+parseFloat(c.css(a,b)),g="number"),!(null==d||"number"===g&&isNaN(d)||("number"!==g||c.cssNumber[k]||(d+="px"),c.support.clearCloneStyle||""!==d||0!==b.indexOf("background")||(l[b]="inherit"),h&&"set"in h&&(d=h.set(a,d,e))===n)))try{l[b]=d}catch(q){}}else return h&&"get"in h&&(f=h.get(a,!1,e))!==n?f:l[b]}},css:function(a,b,d,
e){var f,g;g=c.camelCase(b);b=c.cssProps[g]||(c.cssProps[g]=eb(a.style,g));(g=c.cssHooks[b]||c.cssHooks[g])&&"get"in g&&(f=g.get(a,!0,d));f===n&&(f=N(a,b,e));"normal"===f&&b in Lb&&(f=Lb[b]);return""===d||d?(a=parseFloat(f),!0===d||c.isNumeric(a)?a||0:f):f}});t.getComputedStyle?(I=function(a){return t.getComputedStyle(a,null)},N=function(a,b,d){var e,f=(d=d||I(a))?d.getPropertyValue(b)||d[b]:n,g=a.style;d&&(""!==f||c.contains(a.ownerDocument,a)||(f=c.style(a,b)),oa.test(f)&&Kb.test(b)&&(a=g.width,
b=g.minWidth,e=g.maxWidth,g.minWidth=g.maxWidth=g.width=f,f=d.width,g.width=a,g.minWidth=b,g.maxWidth=e));return f}):p.documentElement.currentStyle&&(I=function(a){return a.currentStyle},N=function(a,b,c){var e,f,g=(c=c||I(a))?c[b]:n,h=a.style;null==g&&h&&h[b]&&(g=h[b]);if(oa.test(g)&&!Fc.test(b)){c=h.left;if(f=(e=a.runtimeStyle)&&e.left)e.left=a.currentStyle.left;h.left="fontSize"===b?"1em":g;g=h.pixelLeft+"px";h.left=c;f&&(e.left=f)}return""===g?"auto":g});c.each(["height","width"],function(a,b){c.cssHooks[b]=
{get:function(a,e,f){if(e)return 0===a.offsetWidth&&Gc.test(c.css(a,"display"))?c.swap(a,Ic,function(){return kb(a,b,f)}):kb(a,b,f)},set:function(a,e,f){var g=f&&I(a);return ib(a,e,f?jb(a,b,f,c.support.boxSizing&&"border-box"===c.css(a,"boxSizing",!1,g),g):0)}}});c.support.opacity||(c.cssHooks.opacity={get:function(a,b){return Ec.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?.01*parseFloat(RegExp.$1)+"":b?"1":""},set:function(a,b){var d=a.style,e=a.currentStyle,f=c.isNumeric(b)?
"alpha(opacity="+100*b+")":"",g=e&&e.filter||d.filter||"";d.zoom=1;(1<=b||""===b)&&""===c.trim(g.replace(Oa,""))&&d.removeAttribute&&(d.removeAttribute("filter"),""===b||e&&!e.filter)||(d.filter=Oa.test(g)?g.replace(Oa,f):g+" "+f)}});c(function(){c.support.reliableMarginRight||(c.cssHooks.marginRight={get:function(a,b){if(b)return c.swap(a,{display:"inline-block"},N,[a,"marginRight"])}});!c.support.pixelPosition&&c.fn.position&&c.each(["top","left"],function(a,b){c.cssHooks[b]={get:function(a,e){if(e)return e=
N(a,b),oa.test(e)?c(a).position()[b]+"px":e}}})});c.expr&&c.expr.filters&&(c.expr.filters.hidden=function(a){return 0>=a.offsetWidth&&0>=a.offsetHeight||!c.support.reliableHiddenOffsets&&"none"===(a.style&&a.style.display||c.css(a,"display"))},c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)});c.each({margin:"",padding:"",border:"Width"},function(a,b){c.cssHooks[a+b]={expand:function(c){var e=0,f={};for(c="string"===typeof c?c.split(" "):[c];4>e;e++)f[a+R[e]+b]=c[e]||c[e-2]||c[0];
return f}};Kb.test(a)||(c.cssHooks[a+b].set=ib)});var Jc=/%20/g,ac=/\[\]$/,Mb=/\r?\n/g,Kc=/^(?:submit|button|image|reset|file)$/i,Lc=/^(?:input|select|textarea|keygen)/i;c.fn.extend({serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=c.prop(this,"elements");return a?c.makeArray(a):this}).filter(function(){var a=this.type;return this.name&&!c(this).is(":disabled")&&Lc.test(this.nodeName)&&!Kc.test(a)&&(this.checked||!Ba.test(a))}).map(function(a,
b){var d=c(this).val();return null==d?null:c.isArray(d)?c.map(d,function(a){return{name:b.name,value:a.replace(Mb,"\r\n")}}):{name:b.name,value:d.replace(Mb,"\r\n")}}).get()}});c.param=function(a,b){var d,e=[],f=function(a,b){b=c.isFunction(b)?b():null==b?"":b;e[e.length]=encodeURIComponent(a)+"="+encodeURIComponent(b)};b===n&&(b=c.ajaxSettings&&c.ajaxSettings.traditional);if(c.isArray(a)||a.jquery&&!c.isPlainObject(a))c.each(a,function(){f(this.name,this.value)});else for(d in a)Ca(d,a[d],b,f);return e.join("&").replace(Jc,
"+")};c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),function(a,b){c.fn[b]=function(a,c){return 0<arguments.length?this.on(b,null,a,c):this.trigger(b)}});c.fn.extend({hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)},bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},
delegate:function(a,b,c,e){return this.on(b,a,c,e)},undelegate:function(a,b,c){return 1===arguments.length?this.off(a,"**"):this.off(b,a||"**",c)}});var aa,P,Pa=c.now(),Qa=/\?/,Mc=/#.*$/,Nb=/([?&])_=[^&]*/,Nc=/^(.*?):[ \t]*([^\r\n]*)\r?$/mg,Oc=/^(?:GET|HEAD)$/,Pc=/^\/\//,Ob=/^([\w.+-]+:)(?:\/\/([^\/?#:]*)(?::(\d+)|)|)/,Pb=c.fn.load,Qb={},Da={},Rb="*/".concat("*");try{P=cc.href}catch(Tc){P=p.createElement("a"),P.href="",P=P.href}aa=Ob.exec(P.toLowerCase())||[];c.fn.load=function(a,b,d){if("string"!==
typeof a&&Pb)return Pb.apply(this,arguments);var e,f,g,h=this,k=a.indexOf(" ");0<=k&&(e=a.slice(k,a.length),a=a.slice(0,k));c.isFunction(b)?(d=b,b=n):b&&"object"===typeof b&&(g="POST");0<h.length&&c.ajax({url:a,type:g,dataType:"html",data:b}).done(function(a){f=arguments;h.html(e?c("<div>").append(c.parseHTML(a)).find(e):a)}).complete(d&&function(a,b){h.each(d,f||[a.responseText,b,a])});return this};c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=
function(a){return this.on(b,a)}});c.extend({active:0,lastModified:{},etag:{},ajaxSettings:{url:P,type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(aa[1]),global:!0,processData:!0,async:!0,contentType:"application/x-www-form-urlencoded; charset=UTF-8",accepts:{"*":Rb,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/xml/,html:/html/,json:/json/},responseFields:{xml:"responseXML",text:"responseText",
json:"responseJSON"},converters:{"* text":String,"text html":!0,"text json":c.parseJSON,"text xml":c.parseXML},flatOptions:{url:!0,context:!0}},ajaxSetup:function(a,b){return b?Ea(Ea(a,c.ajaxSettings),b):Ea(c.ajaxSettings,a)},ajaxPrefilter:nb(Qb),ajaxTransport:nb(Da),ajax:function(a,b){function d(a,b,d,e){var f,p,u,y;y=b;if(2!==D){D=2;k&&clearTimeout(k);q=n;h=e||"";r.readyState=0<a?4:0;e=200<=a&&300>a||304===a;if(d){u=m;for(var J=r,H,K,M,B,A=u.contents,x=u.dataTypes;"*"===x[0];)x.shift(),K===n&&(K=
u.mimeType||J.getResponseHeader("Content-Type"));if(K)for(B in A)if(A[B]&&A[B].test(K)){x.unshift(B);break}if(x[0]in d)M=x[0];else{for(B in d){if(!x[0]||u.converters[B+" "+x[0]]){M=B;break}H||(H=B)}M=M||H}M?(M!==x[0]&&x.unshift(M),u=d[M]):u=void 0}a:{d=m;H=u;K=r;M=e;var I,E,F,J={},A=d.dataTypes.slice();if(A[1])for(E in d.converters)J[E.toLowerCase()]=d.converters[E];for(B=A.shift();B;)if(d.responseFields[B]&&(K[d.responseFields[B]]=H),!F&&M&&d.dataFilter&&(H=d.dataFilter(H,d.dataType)),F=B,B=A.shift())if("*"===
B)B=F;else if("*"!==F&&F!==B){E=J[F+" "+B]||J["* "+B];if(!E)for(I in J)if(u=I.split(" "),u[1]===B&&(E=J[F+" "+u[0]]||J["* "+u[0]])){!0===E?E=J[I]:!0!==J[I]&&(B=u[0],A.unshift(u[1]));break}if(!0!==E)if(E&&d["throws"])H=E(H);else try{H=E(H)}catch(N){u={state:"parsererror",error:E?N:"No conversion from "+F+" to "+B};break a}}u={state:"success",data:H}}if(e)m.ifModified&&((y=r.getResponseHeader("Last-Modified"))&&(c.lastModified[g]=y),(y=r.getResponseHeader("etag"))&&(c.etag[g]=y)),204===a||"HEAD"===
m.type?y="nocontent":304===a?y="notmodified":(y=u.state,f=u.data,p=u.error,e=!p);else if(p=y,a||!y)y="error",0>a&&(a=0);r.status=a;r.statusText=(b||y)+"";e?z.resolveWith(t,[f,y,r]):z.rejectWith(t,[r,y,p]);r.statusCode(G);G=n;l&&L.trigger(e?"ajaxSuccess":"ajaxError",[r,m,e?f:p]);C.fireWith(t,[r,y]);l&&(L.trigger("ajaxComplete",[r,m]),--c.active||c.event.trigger("ajaxStop"))}}"object"===typeof a&&(b=a,a=n);b=b||{};var e,f,g,h,k,l,q,p,m=c.ajaxSetup({},b),t=m.context||m,L=m.context&&(t.nodeType||t.jquery)?
c(t):c.event,z=c.Deferred(),C=c.Callbacks("once memory"),G=m.statusCode||{},A={},I={},D=0,N="canceled",r={readyState:0,getResponseHeader:function(a){var b;if(2===D){if(!p)for(p={};b=Nc.exec(h);)p[b[1].toLowerCase()]=b[2];b=p[a.toLowerCase()]}return null==b?null:b},getAllResponseHeaders:function(){return 2===D?h:null},setRequestHeader:function(a,b){var c=a.toLowerCase();D||(a=I[c]=I[c]||a,A[a]=b);return this},overrideMimeType:function(a){D||(m.mimeType=a);return this},statusCode:function(a){var b;
if(a)if(2>D)for(b in a)G[b]=[G[b],a[b]];else r.always(a[r.status]);return this},abort:function(a){a=a||N;q&&q.abort(a);d(0,a);return this}};z.promise(r).complete=C.add;r.success=r.done;r.error=r.fail;m.url=((a||m.url||P)+"").replace(Mc,"").replace(Pc,aa[1]+"//");m.type=b.method||b.type||m.method||m.type;m.dataTypes=c.trim(m.dataType||"*").toLowerCase().match(F)||[""];null==m.crossDomain&&(e=Ob.exec(m.url.toLowerCase()),m.crossDomain=!(!e||e[1]===aa[1]&&e[2]===aa[2]&&(e[3]||("http:"===e[1]?"80":"443"))===
(aa[3]||("http:"===aa[1]?"80":"443"))));m.data&&m.processData&&"string"!==typeof m.data&&(m.data=c.param(m.data,m.traditional));ob(Qb,m,b,r);if(2===D)return r;(l=m.global)&&0===c.active++&&c.event.trigger("ajaxStart");m.type=m.type.toUpperCase();m.hasContent=!Oc.test(m.type);g=m.url;m.hasContent||(m.data&&(g=m.url+=(Qa.test(g)?"&":"?")+m.data,delete m.data),!1===m.cache&&(m.url=Nb.test(g)?g.replace(Nb,"$1_="+Pa++):g+(Qa.test(g)?"&":"?")+"_="+Pa++));m.ifModified&&(c.lastModified[g]&&r.setRequestHeader("If-Modified-Since",
c.lastModified[g]),c.etag[g]&&r.setRequestHeader("If-None-Match",c.etag[g]));(m.data&&m.hasContent&&!1!==m.contentType||b.contentType)&&r.setRequestHeader("Content-Type",m.contentType);r.setRequestHeader("Accept",m.dataTypes[0]&&m.accepts[m.dataTypes[0]]?m.accepts[m.dataTypes[0]]+("*"!==m.dataTypes[0]?", "+Rb+"; q=0.01":""):m.accepts["*"]);for(f in m.headers)r.setRequestHeader(f,m.headers[f]);if(m.beforeSend&&(!1===m.beforeSend.call(t,r,m)||2===D))return r.abort();N="abort";for(f in{success:1,error:1,
complete:1})r[f](m[f]);if(q=ob(Da,m,b,r)){r.readyState=1;l&&L.trigger("ajaxSend",[r,m]);m.async&&0<m.timeout&&(k=setTimeout(function(){r.abort("timeout")},m.timeout));try{D=1,q.send(A,d)}catch(O){if(2>D)d(-1,O);else throw O;}}else d(-1,"No Transport");return r},getJSON:function(a,b,d){return c.get(a,b,d,"json")},getScript:function(a,b){return c.get(a,n,b,"script")}});c.each(["get","post"],function(a,b){c[b]=function(a,e,f,g){c.isFunction(e)&&(g=g||f,f=e,e=n);return c.ajax({url:a,type:b,dataType:g,
data:e,success:f})}});c.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/(?:java|ecma)script/},converters:{"text script":function(a){c.globalEval(a);return a}}});c.ajaxPrefilter("script",function(a){a.cache===n&&(a.cache=!1);a.crossDomain&&(a.type="GET",a.global=!1)});c.ajaxTransport("script",function(a){if(a.crossDomain){var b,d=p.head||c("head")[0]||p.documentElement;return{send:function(c,f){b=p.createElement("script");
b.async=!0;a.scriptCharset&&(b.charset=a.scriptCharset);b.src=a.url;b.onload=b.onreadystatechange=function(a,c){if(c||!b.readyState||/loaded|complete/.test(b.readyState))b.onload=b.onreadystatechange=null,b.parentNode&&b.parentNode.removeChild(b),b=null,c||f(200,"success")};d.insertBefore(b,d.firstChild)},abort:function(){if(b)b.onload(n,!0)}}}});var Sb=[],Ra=/(=)\?(?=&|$)|\?\?/;c.ajaxSetup({jsonp:"callback",jsonpCallback:function(){var a=Sb.pop()||c.expando+"_"+Pa++;this[a]=!0;return a}});c.ajaxPrefilter("json jsonp",
function(a,b,d){var e,f,g,h=!1!==a.jsonp&&(Ra.test(a.url)?"url":"string"===typeof a.data&&!(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&Ra.test(a.data)&&"data");if(h||"jsonp"===a.dataTypes[0])return e=a.jsonpCallback=c.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback,h?a[h]=a[h].replace(Ra,"$1"+e):!1!==a.jsonp&&(a.url+=(Qa.test(a.url)?"&":"?")+a.jsonp+"="+e),a.converters["script json"]=function(){g||c.error(e+" was not called");return g[0]},a.dataTypes[0]="json",
f=t[e],t[e]=function(){g=arguments},d.always(function(){t[e]=f;a[e]&&(a.jsonpCallback=b.jsonpCallback,Sb.push(e));g&&c.isFunction(f)&&f(g[0]);g=f=n}),"script"});var Q,ma,Qc=0,Sa=t.ActiveXObject&&function(){for(var a in Q)Q[a](n,!0)};c.ajaxSettings.xhr=t.ActiveXObject?function(){var a;if(!(a=!this.isLocal&&pb()))a:{try{a=new t.ActiveXObject("Microsoft.XMLHTTP");break a}catch(b){}a=void 0}return a}:pb;ma=c.ajaxSettings.xhr();c.support.cors=!!ma&&"withCredentials"in ma;(ma=c.support.ajax=!!ma)&&c.ajaxTransport(function(a){if(!a.crossDomain||
c.support.cors){var b;return{send:function(d,e){var f,g,h=a.xhr();a.username?h.open(a.type,a.url,a.async,a.username,a.password):h.open(a.type,a.url,a.async);if(a.xhrFields)for(g in a.xhrFields)h[g]=a.xhrFields[g];a.mimeType&&h.overrideMimeType&&h.overrideMimeType(a.mimeType);a.crossDomain||d["X-Requested-With"]||(d["X-Requested-With"]="XMLHttpRequest");try{for(g in d)h.setRequestHeader(g,d[g])}catch(k){}h.send(a.hasContent&&a.data||null);b=function(d,g){var k,m,p,t;try{if(b&&(g||4===h.readyState))if(b=
n,f&&(h.onreadystatechange=c.noop,Sa&&delete Q[f]),g)4!==h.readyState&&h.abort();else{t={};k=h.status;m=h.getAllResponseHeaders();"string"===typeof h.responseText&&(t.text=h.responseText);try{p=h.statusText}catch(z){p=""}k||!a.isLocal||a.crossDomain?1223===k&&(k=204):k=t.text?200:404}}catch(A){g||e(-1,A)}t&&e(k,p,t,m)};a.async?4===h.readyState?setTimeout(b):(f=++Qc,Sa&&(Q||(Q={},c(t).unload(Sa)),Q[f]=b),h.onreadystatechange=b):b()},abort:function(){b&&b(n,!0)}}}});var U,ua,Rc=/^(?:toggle|show|hide)$/,
Tb=new RegExp("^(?:([+-])=|)("+ra+")([a-z%]*)$","i"),Sc=/queueHooks$/,W=[function(a,b,d){var e,f,g,h,k,l=this,n={},p=a.style,m=a.nodeType&&ha(a),t=c._data(a,"fxshow");d.queue||(h=c._queueHooks(a,"fx"),null==h.unqueued&&(h.unqueued=0,k=h.empty.fire,h.empty.fire=function(){h.unqueued||k()}),h.unqueued++,l.always(function(){l.always(function(){h.unqueued--;c.queue(a,"fx").length||h.empty.fire()})}));1===a.nodeType&&("height"in b||"width"in b)&&(d.overflow=[p.overflow,p.overflowX,p.overflowY],"inline"===
c.css(a,"display")&&"none"===c.css(a,"float")&&(c.support.inlineBlockNeedsLayout&&"inline"!==hb(a.nodeName)?p.zoom=1:p.display="inline-block"));d.overflow&&(p.overflow="hidden",c.support.shrinkWrapBlocks||l.always(function(){p.overflow=d.overflow[0];p.overflowX=d.overflow[1];p.overflowY=d.overflow[2]}));for(e in b)f=b[e],Rc.exec(f)&&(delete b[e],g=g||"toggle"===f,f!==(m?"hide":"show")&&(n[e]=t&&t[e]||c.style(a,e)));if(!c.isEmptyObject(n))for(e in t?"hidden"in t&&(m=t.hidden):t=c._data(a,"fxshow",
{}),g&&(t.hidden=!m),m?c(a).show():l.done(function(){c(a).hide()}),l.done(function(){var b;c._removeData(a,"fxshow");for(b in n)c.style(a,b,n[b])}),n)b=rb(m?t[e]:0,e,l),e in t||(t[e]=b.start,m&&(b.end=b.start,b.start="width"===e||"height"===e?1:0))}],V={"*":[function(a,b){var d=this.createTween(a,b),e=d.cur(),f=Tb.exec(b),g=f&&f[3]||(c.cssNumber[a]?"":"px"),h=(c.cssNumber[a]||"px"!==g&&+e)&&Tb.exec(c.css(d.elem,a)),k=1,l=20;if(h&&h[3]!==g){g=g||h[3];f=f||[];h=+e||1;do k=k||".5",h/=k,c.style(d.elem,
a,h+g);while(k!==(k=d.cur()/e)&&1!==k&&--l)}f&&(h=d.start=+h||+e||0,d.unit=g,d.end=f[1]?h+(f[1]+1)*f[2]:+f[2]);return d}]};c.Animation=c.extend(sb,{tweener:function(a,b){c.isFunction(a)?(b=a,a=["*"]):a=a.split(" ");for(var d,e=0,f=a.length;e<f;e++)d=a[e],V[d]=V[d]||[],V[d].unshift(b)},prefilter:function(a,b){b?W.unshift(a):W.push(a)}});c.Tween=G;G.prototype={constructor:G,init:function(a,b,d,e,f,g){this.elem=a;this.prop=d;this.easing=f||"swing";this.options=b;this.start=this.now=this.cur();this.end=
e;this.unit=g||(c.cssNumber[d]?"":"px")},cur:function(){var a=G.propHooks[this.prop];return a&&a.get?a.get(this):G.propHooks._default.get(this)},run:function(a){var b,d=G.propHooks[this.prop];this.pos=this.options.duration?b=c.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):b=a;this.now=(this.end-this.start)*b+this.start;this.options.step&&this.options.step.call(this.elem,this.now,this);d&&d.set?d.set(this):G.propHooks._default.set(this);return this}};G.prototype.init.prototype=
G.prototype;G.propHooks={_default:{get:function(a){return null==a.elem[a.prop]||a.elem.style&&null!=a.elem.style[a.prop]?(a=c.css(a.elem,a.prop,""))&&"auto"!==a?a:0:a.elem[a.prop]},set:function(a){if(c.fx.step[a.prop])c.fx.step[a.prop](a);else a.elem.style&&(null!=a.elem.style[c.cssProps[a.prop]]||c.cssHooks[a.prop])?c.style(a.elem,a.prop,a.now+a.unit):a.elem[a.prop]=a.now}}};G.propHooks.scrollTop=G.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&(a.elem[a.prop]=a.now)}};
c.each(["toggle","show","hide"],function(a,b){var d=c.fn[b];c.fn[b]=function(a,c,g){return null==a||"boolean"===typeof a?d.apply(this,arguments):this.animate(ca(b,!0),a,c,g)}});c.fn.extend({fadeTo:function(a,b,c,e){return this.filter(ha).css("opacity",0).show().end().animate({opacity:b},a,c,e)},animate:function(a,b,d,e){var f=c.isEmptyObject(a),g=c.speed(b,d,e);b=function(){var b=sb(this,c.extend({},a),g);(f||c._data(this,"finish"))&&b.stop(!0)};b.finish=b;return f||!1===g.queue?this.each(b):this.queue(g.queue,
b)},stop:function(a,b,d){var e=function(a){var b=a.stop;delete a.stop;b(d)};"string"!==typeof a&&(d=b,b=a,a=n);b&&!1!==a&&this.queue(a||"fx",[]);return this.each(function(){var b=!0,g=null!=a&&a+"queueHooks",h=c.timers,k=c._data(this);if(g)k[g]&&k[g].stop&&e(k[g]);else for(g in k)k[g]&&k[g].stop&&Sc.test(g)&&e(k[g]);for(g=h.length;g--;)h[g].elem!==this||null!=a&&h[g].queue!==a||(h[g].anim.stop(d),b=!1,h.splice(g,1));!b&&d||c.dequeue(this,a)})},finish:function(a){!1!==a&&(a=a||"fx");return this.each(function(){var b,
d=c._data(this),e=d[a+"queue"];b=d[a+"queueHooks"];var f=c.timers,g=e?e.length:0;d.finish=!0;c.queue(this,a,[]);b&&b.stop&&b.stop.call(this,!0);for(b=f.length;b--;)f[b].elem===this&&f[b].queue===a&&(f[b].anim.stop(!0),f.splice(b,1));for(b=0;b<g;b++)e[b]&&e[b].finish&&e[b].finish.call(this);delete d.finish})}});c.each({slideDown:ca("show"),slideUp:ca("hide"),slideToggle:ca("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){c.fn[a]=function(a,c,f){return this.animate(b,
a,c,f)}});c.speed=function(a,b,d){var e=a&&"object"===typeof a?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};e.duration=c.fx.off?0:"number"===typeof e.duration?e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;if(null==e.queue||!0===e.queue)e.queue="fx";e.old=e.complete;e.complete=function(){c.isFunction(e.old)&&e.old.call(this);e.queue&&c.dequeue(this,e.queue)};return e};c.easing={linear:function(a){return a},
swing:function(a){return.5-Math.cos(a*Math.PI)/2}};c.timers=[];c.fx=G.prototype.init;c.fx.tick=function(){var a,b=c.timers,d=0;for(U=c.now();d<b.length;d++)a=b[d],a()||b[d]!==a||b.splice(d--,1);b.length||c.fx.stop();U=n};c.fx.timer=function(a){a()&&c.timers.push(a)&&c.fx.start()};c.fx.interval=13;c.fx.start=function(){ua||(ua=setInterval(c.fx.tick,c.fx.interval))};c.fx.stop=function(){clearInterval(ua);ua=null};c.fx.speeds={slow:600,fast:200,_default:400};c.fx.step={};c.expr&&c.expr.filters&&(c.expr.filters.animated=
function(a){return c.grep(c.timers,function(b){return a===b.elem}).length});c.fn.offset=function(a){if(arguments.length)return a===n?this:this.each(function(b){c.offset.setOffset(this,a,b)});var b,d,e={top:0,left:0},f=(d=this[0])&&d.ownerDocument;if(f){b=f.documentElement;if(!c.contains(b,d))return e;typeof d.getBoundingClientRect!==A&&(e=d.getBoundingClientRect());d=tb(f);return{top:e.top+(d.pageYOffset||b.scrollTop)-(b.clientTop||0),left:e.left+(d.pageXOffset||b.scrollLeft)-(b.clientLeft||0)}}};
c.offset={setOffset:function(a,b,d){var e=c.css(a,"position");"static"===e&&(a.style.position="relative");var f=c(a),g=f.offset(),h=c.css(a,"top"),k=c.css(a,"left"),l={},n={};("absolute"===e||"fixed"===e)&&-1<c.inArray("auto",[h,k])?(n=f.position(),e=n.top,k=n.left):(e=parseFloat(h)||0,k=parseFloat(k)||0);c.isFunction(b)&&(b=b.call(a,d,g));null!=b.top&&(l.top=b.top-g.top+e);null!=b.left&&(l.left=b.left-g.left+k);"using"in b?b.using.call(a,l):f.css(l)}};c.fn.extend({position:function(){if(this[0]){var a,
b,d={top:0,left:0},e=this[0];"fixed"===c.css(e,"position")?b=e.getBoundingClientRect():(a=this.offsetParent(),b=this.offset(),c.nodeName(a[0],"html")||(d=a.offset()),d.top+=c.css(a[0],"borderTopWidth",!0),d.left+=c.css(a[0],"borderLeftWidth",!0));return{top:b.top-d.top-c.css(e,"marginTop",!0),left:b.left-d.left-c.css(e,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||vb;a&&!c.nodeName(a,"html")&&"static"===c.css(a,"position");)a=a.offsetParent;return a||
vb})}});c.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var d=/Y/.test(b);c.fn[a]=function(e){return c.access(this,function(a,e,h){var k=tb(a);if(h===n)return k?b in k?k[b]:k.document.documentElement[e]:a[e];k?k.scrollTo(d?c(k).scrollLeft():h,d?h:c(k).scrollTop()):a[e]=h},a,e,arguments.length,null)}});c.each({Height:"height",Width:"width"},function(a,b){c.each({padding:"inner"+a,content:b,"":"outer"+a},function(d,e){c.fn[e]=function(e,g){var h=arguments.length&&(d||"boolean"!==
typeof e),k=d||(!0===e||!0===g?"margin":"border");return c.access(this,function(b,d,e){return c.isWindow(b)?b.document.documentElement["client"+a]:9===b.nodeType?(d=b.documentElement,Math.max(b.body["scroll"+a],d["scroll"+a],b.body["offset"+a],d["offset"+a],d["client"+a])):e===n?c.css(b,d,k):c.style(b,d,e,k)},b,h?e:n,h,null)}})});c.fn.size=function(){return this.length};c.fn.andSelf=c.fn.addBack;"object"===typeof module&&module&&"object"===typeof module.exports?module.exports=c:(t.jQuery=t.$=c,"function"===
typeof define&&define.amd&&define("jquery",[],function(){return c}))})(window);
